C
C**********************************************************************C
C**********************************************************************C
C**********************************************************************C
C
      REAL FUNCTION CSEDRESB(DENBULK,WRSPO,VDRO,VDR,VDRC,IOPT)
C
C **  THIS SUBROUTINE IS PART OF  EFDC-FULL VERSION 1.0a 
C
C **  LAST MODIFIED BY JOHN HAMRICK ON 1 NOVEMBER 2001
C
C----------------------------------------------------------------------C
C
C CHANGE RECORD
C DATE MODIFIED     BY                 DATE APPROVED    BY
C
C----------------------------------------------------------------------C
C
      INCLUDE 'EFDC.PAR'
C
C **  CALCULATES BULK EROSION RATE OF COHESIVE 
C **  SEDIMENT AS A FUNCTION OF BED BULK DENSITY AND OTHER VARIABLES
C **  CURRENT OPTIONS SHOULD NOT BE USED
C
C **  IOPT=1  BASED ON 
C **
C **  HWANG, K. N., AND A. J. MEHTA, 1989: FINE SEDIMENT ERODIBILITY
C **  IN LAKE OKEECHOBEE FLORIDA. COASTAL AND OCEANOGRAPHIC ENGINEERING
C **  DEPARTMENT, UNIVERSITY OF FLORIDA, GAINESVILLE, FL32661
C
C **  IOPT=2  BASED ON J. M. HAMRICK'S MODIFICATION OF
C **
C **  SANFORD, L.P., AND J. P. Y. MAA, 2001: A UNIFIED EROSION FORMULATION
C **  FOR FINE SEDIMENT, MARINE GEOLOGY, 179, 9-23.
C
      IF(IOPT.GE.1)CSEDRESB=0.0
C
C      IF(IOPT.EQ.1)THEN
C        DENBULK=0.001*DENBULK
C        IF(DENBULK.LE.1.065)THEN
C          CSEDRESB=0.62
C        ELSE
C          TMP=0.198/(DENBULK-1.0023)
C          TMP=EXP(TMP)
C          CSEDRESB=6.4E-4*(10.**TMP)
C        ENDIF
C      ENDIF
C
C      IF(IOPT.EQ.2)THEN
C        CSEDRESB=WRSPO*(1.+VDRO)/(1.+VDR)
C      ENDIF
C
C      IF(IOPT.EQ.3)THEN
C        CSEDRESB=WRSPO*(1.+VDRO)/(1.+VDRC)
C      ENDIF
C
C      IF(IOPT.EQ.99)THEN
C        CSEDRESB=WRSPO
C      ENDIF
C
      RETURN
      END
