C
C**********************************************************************C
C**********************************************************************C
C**********************************************************************C
C
      SUBROUTINE LVELPLTV
C
C **  THIS SUBROUTINE IS PART OF  EFDC-FULL VERSION 1.0a 
C
C **  LAST MODIFIED BY JOHN HAMRICK ON 1 NOVEMBER 2001
C
C----------------------------------------------------------------------C
C
C CHANGE RECORD
C DATE MODIFIED     BY                 DATE APPROVED    BY
C
C----------------------------------------------------------------------C
C
C **  SUBROUTINE VELPLTV WRITES A FILE FOR VERTICAL PLANE CONTOURING
C **  OF VELOCITY NORMAL TO AN ARBITARY SEQUENCE OF (I,J) POINTS AND
C **  AND VERTICAL PLANE TANGENTIAL-VERTICAL VELOCITY VECTORS
C
C**********************************************************************C
C
      INCLUDE 'EFDC.PAR'
      INCLUDE 'EFDC.CMN'
C
C**********************************************************************C
C
      REAL RVELN (KCM,100)
      REAL RVELT (KCM,100)
      REAL RW (KCM,100),HLRAVG(LCM)
C
      CHARACTER*80 TITLE10,TITLE20
      CHARACTER*80 TITLE40,TITLE50
      CHARACTER*80 TITLE70,TITLE80
C
C**********************************************************************C
C
C **  WRITE HEADINGS
C
      TITLE10='NORMAL LAG MEAN VEL CONTOURS'
      TITLE20='NORMAL AVG LAG MEAN VEL CONTOURS'
      TITLE40='TANGENTIAL LAG MEAN VEL CONTOURS'
      TITLE50='TANGENTIAL AVG LAG MEAN VEL CONTOURS'
      TITLE70='TANGENTIAL LAG MEAN VEL VECTORS'
      TITLE80='TANGENTIAL AVG LAG MEAN VEL VECTORS'
C
      LEVELS=KC
C
      IF(ISECVPV.GE.1)THEN
        OPEN(11,FILE='LMVCNV1.OUT',STATUS='UNKNOWN')
        OPEN(21,FILE='ALVCNV1.OUT',STATUS='UNKNOWN')
        OPEN(41,FILE='LMVCVT1.OUT',STATUS='UNKNOWN')
        OPEN(51,FILE='ALVCVT1.OUT',STATUS='UNKNOWN')
        OPEN(71,FILE='LMVVCV1.OUT',STATUS='UNKNOWN')
        OPEN(81,FILE='ALVVCV1.OUT',STATUS='UNKNOWN')
        CLOSE(11,STATUS='DELETE')
        CLOSE(21,STATUS='DELETE')
        CLOSE(41,STATUS='DELETE')
        CLOSE(51,STATUS='DELETE')
        CLOSE(71,STATUS='DELETE')
        CLOSE(81,STATUS='DELETE')
        OPEN(11,FILE='LMVCNV1.OUT',STATUS='UNKNOWN')
        OPEN(21,FILE='ALVCNV1.OUT',STATUS='UNKNOWN')
        OPEN(41,FILE='LMVCVT1.OUT',STATUS='UNKNOWN')
        OPEN(51,FILE='ALVCVT1.OUT',STATUS='UNKNOWN')
        OPEN(71,FILE='LMVVCV1.OUT',STATUS='UNKNOWN')
        OPEN(81,FILE='ALVVCV1.OUT',STATUS='UNKNOWN')
      ENDIF 
      IF(ISECVPV.GE.2)THEN
        OPEN(12,FILE='LMVCNV2.OUT',STATUS='UNKNOWN')
        OPEN(22,FILE='ALVCNV2.OUT',STATUS='UNKNOWN')
        OPEN(42,FILE='LMVCVT2.OUT',STATUS='UNKNOWN')
        OPEN(52,FILE='ALVCVT2.OUT',STATUS='UNKNOWN')
        OPEN(72,FILE='LMVVCV2.OUT',STATUS='UNKNOWN')
        OPEN(82,FILE='ALVVCV2.OUT',STATUS='UNKNOWN')
        CLOSE(12,STATUS='DELETE')
        CLOSE(22,STATUS='DELETE')
        CLOSE(42,STATUS='DELETE')
        CLOSE(52,STATUS='DELETE')
        CLOSE(72,STATUS='DELETE')
        CLOSE(82,STATUS='DELETE')
        OPEN(12,FILE='LMVCNV2.OUT',STATUS='UNKNOWN')
        OPEN(22,FILE='ALVCNV2.OUT',STATUS='UNKNOWN')
        OPEN(42,FILE='LMVCVT2.OUT',STATUS='UNKNOWN')
        OPEN(52,FILE='ALVCVT2.OUT',STATUS='UNKNOWN')
        OPEN(72,FILE='LMVVCV2.OUT',STATUS='UNKNOWN')
        OPEN(82,FILE='ALVVCV2.OUT',STATUS='UNKNOWN')
      ENDIF
      IF(ISECVPV.GE.3)THEN
        OPEN(13,FILE='LMVCNV3.OUT',STATUS='UNKNOWN')
        OPEN(23,FILE='ALVCNV3.OUT',STATUS='UNKNOWN')
        OPEN(43,FILE='LMVCVT3.OUT',STATUS='UNKNOWN')
        OPEN(53,FILE='ALVCVT3.OUT',STATUS='UNKNOWN')
        OPEN(73,FILE='LMVVCV3.OUT',STATUS='UNKNOWN')
        OPEN(83,FILE='ALVVCV3.OUT',STATUS='UNKNOWN')
        CLOSE(13,STATUS='DELETE')
        CLOSE(23,STATUS='DELETE')
        CLOSE(43,STATUS='DELETE')
        CLOSE(53,STATUS='DELETE')
        CLOSE(73,STATUS='DELETE')
        CLOSE(83,STATUS='DELETE')
        OPEN(13,FILE='LMVCNV3.OUT',STATUS='UNKNOWN')
        OPEN(23,FILE='ALVCNV3.OUT',STATUS='UNKNOWN')
        OPEN(43,FILE='LMVCVT3.OUT',STATUS='UNKNOWN')
        OPEN(53,FILE='ALVCVT3.OUT',STATUS='UNKNOWN')
        OPEN(73,FILE='LMVVCV3.OUT',STATUS='UNKNOWN')
        OPEN(83,FILE='ALVVCV3.OUT',STATUS='UNKNOWN')
      ENDIF
      IF(ISECVPV.GE.4)THEN
        OPEN(14,FILE='LMVCNV4.OUT',STATUS='UNKNOWN')
        OPEN(24,FILE='ALVCNV4.OUT',STATUS='UNKNOWN')
        OPEN(44,FILE='LMVCVT4.OUT',STATUS='UNKNOWN')
        OPEN(54,FILE='ALVCVT4.OUT',STATUS='UNKNOWN')
        OPEN(74,FILE='LMVVCV4.OUT',STATUS='UNKNOWN')
        OPEN(84,FILE='ALVVCV4.OUT',STATUS='UNKNOWN')
        CLOSE(14,STATUS='DELETE')
        CLOSE(24,STATUS='DELETE')
        CLOSE(44,STATUS='DELETE')
        CLOSE(54,STATUS='DELETE')
        CLOSE(74,STATUS='DELETE')
        CLOSE(84,STATUS='DELETE')
        OPEN(14,FILE='LMVCNV4.OUT',STATUS='UNKNOWN')
        OPEN(24,FILE='ALVCNV4.OUT',STATUS='UNKNOWN')
        OPEN(44,FILE='LMVCVT4.OUT',STATUS='UNKNOWN')
        OPEN(54,FILE='ALVCVT4.OUT',STATUS='UNKNOWN')
        OPEN(74,FILE='LMVVCV4.OUT',STATUS='UNKNOWN')
        OPEN(84,FILE='ALVVCV4.OUT',STATUS='UNKNOWN')
      ENDIF 
      IF(ISECVPV.GE.5)THEN
        OPEN(15,FILE='LMVCNV5.OUT',STATUS='UNKNOWN')
        OPEN(25,FILE='ALVCNV5.OUT',STATUS='UNKNOWN')
        OPEN(45,FILE='LMVCVT5.OUT',STATUS='UNKNOWN')
        OPEN(55,FILE='ALVCVT5.OUT',STATUS='UNKNOWN')
        OPEN(75,FILE='LMVVCV5.OUT',STATUS='UNKNOWN')
        OPEN(85,FILE='ALVVCV5.OUT',STATUS='UNKNOWN')
        CLOSE(15,STATUS='DELETE')
        CLOSE(25,STATUS='DELETE')
        CLOSE(45,STATUS='DELETE')
        CLOSE(55,STATUS='DELETE')
        CLOSE(75,STATUS='DELETE')
        CLOSE(85,STATUS='DELETE')
        OPEN(15,FILE='LMVCNV5.OUT',STATUS='UNKNOWN')
        OPEN(25,FILE='ALVCNV5.OUT',STATUS='UNKNOWN')
        OPEN(45,FILE='LMVCVT5.OUT',STATUS='UNKNOWN')
        OPEN(55,FILE='ALVCVT5.OUT',STATUS='UNKNOWN')
        OPEN(75,FILE='LMVVCV5.OUT',STATUS='UNKNOWN')
        OPEN(85,FILE='ALVVCV5.OUT',STATUS='UNKNOWN')
      ENDIF
      IF(ISECVPV.GE.6)THEN
        OPEN(16,FILE='LMVCNV6.OUT',STATUS='UNKNOWN')
        OPEN(26,FILE='ALVCNV6.OUT',STATUS='UNKNOWN')
        OPEN(46,FILE='LMVCVT6.OUT',STATUS='UNKNOWN')
        OPEN(56,FILE='ALVCVT6.OUT',STATUS='UNKNOWN')
        OPEN(76,FILE='LMVVCV6.OUT',STATUS='UNKNOWN')
        OPEN(86,FILE='ALVVCV6.OUT',STATUS='UNKNOWN')
        CLOSE(16,STATUS='DELETE')
        CLOSE(26,STATUS='DELETE')
        CLOSE(46,STATUS='DELETE')
        CLOSE(56,STATUS='DELETE')
        CLOSE(76,STATUS='DELETE')
        CLOSE(86,STATUS='DELETE')
        OPEN(16,FILE='LMVCNV6.OUT',STATUS='UNKNOWN')
        OPEN(26,FILE='ALVCNV6.OUT',STATUS='UNKNOWN')
        OPEN(46,FILE='LMVCVT6.OUT',STATUS='UNKNOWN')
        OPEN(56,FILE='ALVCVT6.OUT',STATUS='UNKNOWN')
        OPEN(76,FILE='LMVVCV6.OUT',STATUS='UNKNOWN')
        OPEN(86,FILE='ALVVCV6.OUT',STATUS='UNKNOWN')
      ENDIF
      IF(ISECVPV.GE.7)THEN
        OPEN(17,FILE='LMVCNV7.OUT',STATUS='UNKNOWN')
        OPEN(27,FILE='ALVCNV7.OUT',STATUS='UNKNOWN')
        OPEN(47,FILE='LMVCVT7.OUT',STATUS='UNKNOWN')
        OPEN(57,FILE='ALVCVT7.OUT',STATUS='UNKNOWN')
        OPEN(77,FILE='LMVVCV7.OUT',STATUS='UNKNOWN')
        OPEN(87,FILE='ALVVCV7.OUT',STATUS='UNKNOWN')
        CLOSE(17,STATUS='DELETE')
        CLOSE(27,STATUS='DELETE')
        CLOSE(47,STATUS='DELETE')
        CLOSE(57,STATUS='DELETE')
        CLOSE(77,STATUS='DELETE')
        CLOSE(87,STATUS='DELETE')
        OPEN(17,FILE='LMVCNV7.OUT',STATUS='UNKNOWN')
        OPEN(27,FILE='ALVCNV7.OUT',STATUS='UNKNOWN')
        OPEN(47,FILE='LMVCVT7.OUT',STATUS='UNKNOWN')
        OPEN(57,FILE='ALVCVT7.OUT',STATUS='UNKNOWN')
        OPEN(77,FILE='LMVVCV7.OUT',STATUS='UNKNOWN')
        OPEN(87,FILE='ALVVCV7.OUT',STATUS='UNKNOWN')
      ENDIF 
      IF(ISECVPV.GE.8)THEN
        OPEN(18,FILE='LMVCNV8.OUT',STATUS='UNKNOWN')
        OPEN(28,FILE='ALVCNV8.OUT',STATUS='UNKNOWN')
        OPEN(48,FILE='LMVCVT8.OUT',STATUS='UNKNOWN')
        OPEN(58,FILE='ALVCVT8.OUT',STATUS='UNKNOWN')
        OPEN(78,FILE='LMVVCV8.OUT',STATUS='UNKNOWN')
        OPEN(88,FILE='ALVVCV8.OUT',STATUS='UNKNOWN')
        CLOSE(18,STATUS='DELETE')
        CLOSE(28,STATUS='DELETE')
        CLOSE(48,STATUS='DELETE')
        CLOSE(58,STATUS='DELETE')
        CLOSE(78,STATUS='DELETE')
        CLOSE(88,STATUS='DELETE')
        OPEN(18,FILE='LMVCNV8.OUT',STATUS='UNKNOWN')
        OPEN(28,FILE='ALVCNV8.OUT',STATUS='UNKNOWN')
        OPEN(48,FILE='LMVCVT8.OUT',STATUS='UNKNOWN')
        OPEN(58,FILE='ALVCVT8.OUT',STATUS='UNKNOWN')
        OPEN(78,FILE='LMVVCV8.OUT',STATUS='UNKNOWN')
        OPEN(88,FILE='ALVVCV8.OUT',STATUS='UNKNOWN')
      ENDIF
      IF(ISECVPV.GE.9)THEN
        OPEN(19,FILE='LMVCNV9.OUT',STATUS='UNKNOWN')
        OPEN(29,FILE='ALVCNV9.OUT',STATUS='UNKNOWN')
        OPEN(49,FILE='LMVCVT9.OUT',STATUS='UNKNOWN')
        OPEN(59,FILE='ALVCVT9.OUT',STATUS='UNKNOWN')
        OPEN(79,FILE='LMVVCV9.OUT',STATUS='UNKNOWN')
        OPEN(89,FILE='ALVVCV9.OUT',STATUS='UNKNOWN')
        CLOSE(19,STATUS='DELETE')
        CLOSE(29,STATUS='DELETE')
        CLOSE(49,STATUS='DELETE')
        CLOSE(59,STATUS='DELETE')
        CLOSE(79,STATUS='DELETE')
        CLOSE(89,STATUS='DELETE')
        OPEN(19,FILE='LMVCNV9.OUT',STATUS='UNKNOWN')
        OPEN(29,FILE='ALVCNV9.OUT',STATUS='UNKNOWN')
        OPEN(49,FILE='LMVCVT9.OUT',STATUS='UNKNOWN')
        OPEN(59,FILE='ALVCVT9.OUT',STATUS='UNKNOWN')
        OPEN(79,FILE='LMVVCV9.OUT',STATUS='UNKNOWN')
        OPEN(89,FILE='ALVVCV9.OUT',STATUS='UNKNOWN')
      ENDIF
C
      DO IS=1,ISECVPV
      LUN1=10+IS
      LUN2=20+IS
      LUN4=40+IS
      LUN5=50+IS
      LUN7=70+IS
      LUN8=80+IS
      LINES=NIJVPV(IS)
      WRITE (LUN1,99) TITLE10,CVTITLE(LUN1)
      WRITE (LUN2,99) TITLE20,CVTITLE(LUN2)
      WRITE (LUN4,99) TITLE40,CVTITLE(LUN4)
      WRITE (LUN5,99) TITLE50,CVTITLE(LUN5)
      WRITE (LUN7,99) TITLE70,CVTITLE(LUN7)
      WRITE (LUN8,99) TITLE80,CVTITLE(LUN8)
      WRITE (LUN1,101)LINES,LEVELS
      WRITE (LUN2,101)LINES,LEVELS
      WRITE (LUN4,101)LINES,LEVELS
      WRITE (LUN5,101)LINES,LEVELS
      WRITE (LUN7,101)LINES,LEVELS
      WRITE (LUN8,101)LINES,LEVELS
      WRITE (LUN1,250)(ZZ(K),K=1,KC)
      WRITE (LUN2,250)(ZZ(K),K=1,KC)
      WRITE (LUN4,250)(ZZ(K),K=1,KC)
      WRITE (LUN5,250)(ZZ(K),K=1,KC)
      WRITE (LUN7,250)(ZZ(K),K=1,KC)
      WRITE (LUN8,250)(ZZ(K),K=1,KC)
      ENDDO
C
C----------------------------------------------------------------------C
C
      DO M=1,MLRPDRT
C
      DO IS=1,ISECVPV
      LUN1=10+IS
      LUN4=40+IS
      LUN7=70+IS
      WRITE (LUN1,100)NLRPDRT(M)
      WRITE (LUN4,100)NLRPDRT(M)
      WRITE (LUN7,100)NLRPDRT(M)
      COSC=COS(PI*ANGVPV(IS)/180.)
      SINC=SIN(PI*ANGVPV(IS)/180.)
       DO NN=1,NIJVPV(IS)
       I=IVPV(NN,IS)
       J=JVPV(NN,IS)
       L=LIJ(I,J)
        DO K=1,KC
        RVELN(K,NN)=100.*(XLRPD(NLRPDL(L),K,M)*COSC
     &            +YLRPD(NLRPDL(L),K,M)*SINC)
        RVELT(K,NN)=-100.*XLRPD(NLRPDL(L),K,M)*SINC
     &            +100.*YLRPD(NLRPDL(L),K,M)*COSC
        RW(K,NN)=100.*ZLRPD(NLRPDL(L),K,M)
        ENDDO
       ENDDO
       DO NN=1,NIJVPV(IS)
       I=IVPV(NN,IS)
       J=JVPV(NN,IS)
       L=LIJ(I,J)
       ZETA=HLPF(L)-HMP(L)
       HBTMP=HMP(L)
C      HBTMP=SHPLTV*HMP(L)+SBPLTV*BELV(L)
C      WRITE(LUN1,200)IL(L),JL(L),DLON(L),DLAT(L),ZETA,HMP(L)
C      WRITE(LUN4,200)IL(L),JL(L),DLON(L),DLAT(L),ZETA,HMP(L)
C      WRITE(LUN7,200)IL(L),JL(L),DLON(L),DLAT(L),ZETA,HMP(L)
       WRITE(LUN1,200)IL(L),JL(L),DLON(L),DLAT(L),ZETA,HBTMP
       WRITE(LUN4,200)IL(L),JL(L),DLON(L),DLAT(L),ZETA,HBTMP
       WRITE(LUN7,200)IL(L),JL(L),DLON(L),DLAT(L),ZETA,HBTMP
       WRITE(LUN1,250)(RVELN(K,NN),K=1,KC)
       WRITE(LUN4,250)(RVELT(K,NN),K=1,KC)
       WRITE(LUN7,250)(RVELT(K,NN),K=1,KC)
       WRITE(LUN7,250)(RW(K,NN),K=1,KC)
       ENDDO
      ENDDO
C
      ENDDO
C
      DO IS=1,ISECVPV
      LUN1=10+IS
      LUN4=40+IS
      LUN7=70+IS
      CLOSE(LUN1)
      CLOSE(LUN4)
      CLOSE(LUN7)
      ENDDO
C
C----------------------------------------------------------------------C
C     
      DO NLR=1,NLRPD
      HLRAVG(NLR)=0.
      ENDDO
      DO M=1,MLRPDRT
      DO NLR=1,NLRPD
      HLRAVG(NLR)=HLRAVG(NLR)+HLRPD(NLR,M)
      ENDDO
      ENDDO
      DO NLR=1,NLRPD
      HLRAVG(NLR)=HLRAVG(NLR)/FLOAT(MLRPDRT)
      ENDDO
C     
      M=MLRAVG
C
      DO IS=1,ISECVPV
      LUN2=20+IS
      LUN5=50+IS
      LUN8=80+IS
      WRITE (LUN2,100)N
      WRITE (LUN5,100)N
      WRITE (LUN8,100)N
      COSC=COS(PI*ANGVPV(IS)/180.)
      SINC=SIN(PI*ANGVPV(IS)/180.)
       DO NN=1,NIJVPV(IS)
       I=IVPV(NN,IS)
       J=JVPV(NN,IS)
       L=LIJ(I,J)
        DO K=1,KC
        RVELN(K,NN)=100.*(XLRPD(NLRPDL(L),K,M)*COSC
     &            +YLRPD(NLRPDL(L),K,M)*SINC)
        RVELT(K,NN)=-100.*XLRPD(NLRPDL(L),K,M)*SINC
     &            +100.*YLRPD(NLRPDL(L),K,M)*COSC
        RW(K,NN)=100.*ZLRPD(NLRPDL(L),K,M)
        ENDDO
       ENDDO
       DO NN=1,NIJVPV(IS)
       I=IVPV(NN,IS)
       J=JVPV(NN,IS)
       L=LIJ(I,J)
       ZETA=HLPF(L)-HMP(L)
       HBTMP=HMP(L)
C      HBTMP=SHPLTV*HMP(L)+SBPLTV*BELV(L)
C      WRITE(LUN2,200)IL(L),JL(L),DLON(L),DLAT(L),ZETA,HMP(L)
C      WRITE(LUN5,200)IL(L),JL(L),DLON(L),DLAT(L),ZETA,HMP(L)
C      WRITE(LUN8,200)IL(L),JL(L),DLON(L),DLAT(L),ZETA,HMP(L)
       WRITE(LUN2,200)IL(L),JL(L),DLON(L),DLAT(L),ZETA,HBTMP
       WRITE(LUN5,200)IL(L),JL(L),DLON(L),DLAT(L),ZETA,HBTMP
       WRITE(LUN8,200)IL(L),JL(L),DLON(L),DLAT(L),ZETA,HBTMP
       WRITE(LUN2,250)(RVELN(K,NN),K=1,KC)
       WRITE(LUN5,250)(RVELT(K,NN),K=1,KC)
       WRITE(LUN8,250)(RVELT(K,NN),K=1,KC)
       WRITE(LUN8,250)(RW(K,NN),K=1,KC)
       ENDDO
      CLOSE(LUN2)
      CLOSE(LUN5)
      CLOSE(LUN8)
      ENDDO
C
C**********************************************************************C
C
   99 FORMAT(A40,2X,A20)
  100 FORMAT(I10)
  101 FORMAT(2I10)
  200 FORMAT(2I5,1X,6E14.6)
  250 FORMAT(12E12.4)
CMRM  200 FORMAT(2I5,1X,1P,6E13.5) 
CMRM  250 FORMAT(1P,12E11.3)
C
C**********************************************************************C
C
      RETURN
      END
