C
C**********************************************************************C
C**********************************************************************C
C**********************************************************************C
C
      SUBROUTINE RWQC1(IWQDT)
C
C**********************************************************************C
C
C **  MODIFIED BY J.S. ON 5/5/98 TO ADD A MACALGAL.
C
C **  LAST MODIFIED BY JOHN HAMRICK AND MIKE MORTON ON 8 AUGUST 2001
C
C **  THIS SUBROUTINE IS PART OF  EFDC-FULL VERSION 1.0a 
C
C **  LAST MODIFIED BY JOHN HAMRICK ON 1 NOVEMBER 2001
C
C----------------------------------------------------------------------C
C
C CHANGE RECORD
C DATE MODIFIED     BY                 DATE APPROVED    BY
C
C----------------------------------------------------------------------C
C
C
C**********************************************************************C
C
C READ IN FROM THE UNIT #8
C: I/O CONTROL VARIABLES
C: SPATIALLY AND TEMPORALLY CONSTANT REAL PARAMETERS
C
C**********************************************************************C
C
      INCLUDE 'EFDC.PAR'
      INCLUDE 'EFDC.CMN'
C
      PARAMETER (CONV1=1.0E3,CONV2=8.64E4)

      DIMENSION XPSL(NWQVM),XDSL(NWQVM)
      INTEGER ISSKIP
      CHARACTER TITLE(5)*79, CCMRM*1
C     CHARACTER TITLE(5)*79, RSTOFN*50
C      CHARACTER*50 ICIFN,AGRFN,STLFN,SUNFN,BENFN,PSLFN,NPLFN,NCOFN
C      CHARACTER TITLE(3)*79
C
      OPEN(2,FILE='WQ3D.OUT',STATUS='UNKNOWN',POSITION='APPEND')
C
      OPEN(1,FILE='WQ3DWC.INP',STATUS='UNKNOWN')
C
C READ FIRST LINE IN WQ3DWC.INP FILE.  IF FIRST CHARACTER IS '#', THEN
C THIS IS THE NEW VERSION WITH ANNOTATED COMMENTS ADDED (I.E., USES THE
C SKIPCOMM SUBROUTINE TO SKIP COMMENT LINES.  COMMENT LINES BEGIN WITH
C A "C", "C", OR "#" CHARACTER IN COLUMN 1.  IF "#" IS NOT FOUND AS THE
C FIRST CHARACTER IN THE FILE, THEN THE OLD METHOD OF READING THE
C WQ3DWC.INP FILE IS USED TO PRESERVE BACKWARD COMPATABILITY.
C
      ISSKIP = 0
      READ(1,'(A1)') CCMRM
      BACKSPACE(1)
      IF(CCMRM .EQ. '#') ISSKIP = 1
      CCMRM = '#'
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) (TITLE(M), M=1,3)
      WRITE(2,90) (TITLE(M), M=1,3)

C I/O CONTROL VARIABLES

C      READ(1,999)
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) ISWQLVL,NWQV,NWQZ,NWQPS,NWQTD,NWQTS,NTSWQV,NSMG,NSMZ,
     &          NTSSMV,NSMTS,NWQKDPT
      WRITE(2,*) ISWQLVL,NWQV,NWQZ,NWQPS,NWQTD,NWQTS,NTSWQV,NSMG,NSMZ,
     &          NTSSMV,NSMTS,NWQKDPT
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) (ISTRWQ(NV),NV=1,NWQV)
      WRITE(2,*) (ISTRWQ(NV),NV=1,NWQV)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) IWQDT,IWQM,IWQBEN,IWQSI,IWQFCB,IWQSRP,IWQSTOX,
     +  IWQKA(1), IWQVLIM
      WRITE(2,*) IWQDT,IWQM,IWQBEN,IWQSI,IWQFCB,IWQSRP,IWQSTOX,
     +  IWQKA(1), IWQVLIM
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
C4
C MODIFIED BY J.S.
C
      READ(1,*) IWQZ,IWQNC,IWQRST,NDMWQ,LDMWQ,NDDOAVG,NDLTAVG,IDNOTRVA
      WRITE(2,*) IWQZ,IWQNC,IWQRST,NDMWQ,LDMWQ,NDDOAVG,NDLTAVG,IDNOTRVA
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) IWQICI,IWQAGR,IWQSTL,IWQSUN,IWQPSL,IWQNPL, ISDIURDO,
     &          WQDIUDT, IWQKIN
      WRITE(2,*) IWQICI,IWQAGR,IWQSTL,IWQSUN,IWQPSL,IWQNPL, ISDIURDO,
     &          WQDIUDT, IWQKIN
C     &          ISDIURDO,  ISDIUDIA, ICDIA, JCDIA
C     ISDIURDO > 0 TURNS ON DIURNAL DO OUTPUT TO BINARY FILE
C     WQDIUDT = TIME INTERVAL FOR WRITING TO DIURNAL DO FILE (HOURS)
C
      IWQDIUDT = NINT(WQDIUDT*3600.0/DT)
      WRITE(2,83)': FREQUENCY OF DIURNAL DO OUTPUT (IN DT UNIT) =',
     &  IWQDIUDT
C
      WRITE(2,83)'* IWQDT (DTWQ(D) = DT(S)*IWQDT/86400)        = ',
     &    IWQDT
      DTD = DT/86400.0
	IF(ITIMSOL.EQ.0)THEN
C        DTWQ = DTD*REAL(IWQDT)*REAL(NWQKDPT)
        DTWQ = 2.*DTD*REAL(NWQKDPT)
	  IF(IWQDT.EQ.1) WRITE(6,*)'IWQDT RESET TO 2 FOR 3TL HYDRO'
        DTWQO2 = DTWQ*0.5
	ENDIF
	IF(ITIMSOL.EQ.1)THEN
C        DTWQ = DTD*REAL(IWQDT)*REAL(NWQKDPT)
        DTWQ = DTD*REAL(NWQKDPT)
	  IF(IWQDT.EQ.2) WRITE(6,*)'IWQDT RESET TO 1 FOR 2TL HYDRO'
        DTWQO2 = DTWQ*0.5
	ENDIF
C
      IF(IWQM.EQ.1)THEN
        WRITE(2,80)'* FULL VERSION WITH 21 VARIABLES IS ACTIVATED     '
       ELSE IF(IWQM.EQ.2)THEN
        WRITE(2,80)'* SMALL VERSION WITH 9 VARIABLES IS ACTIVATED     '
       ELSE
        STOP '** ERROR!!! INVALID IWQM VALUE **'
      ENDIF
C
      IF(IWQBEN.EQ.1)THEN
        WRITE(2,80)'* SEDIMENT PROCESS MODEL IS ACTIVATED             '
       ELSE IF(IWQBEN.EQ.0)THEN
        WRITE(2,80)'* SPATIALLY/TEMPORALLY CONSTANT BF IS SPECIFIED   '
       ELSE IF(IWQBEN.EQ.2)THEN
        WRITE(2,80)'* SPATIALLY AND/OR TEMPORALLY-VARYING BF SPECIFIED'
       ELSE
        STOP '** ERROR!!! INVALID IWQBEN VALUE **'
      ENDIF
C
      IF(IWQSI.EQ.1)THEN
        WRITE(2,80)'* SILICA STATE VARIABLES (SU & SA) ARE MODELED    '
        IF(IWQM.EQ.2) STOP '** ERROR!!! INCOMPATIBLE IWQM & IWQSI'
       ELSE
        WRITE(2,80)'* NO SILICA (SU & SU) LIMITATION                  '
      ENDIF
C
      IF(IWQFCB.EQ.1)THEN
        WRITE(2,80)'* FCB (FECAL COLIFORM BACTERIA) IS MODELED        '
       ELSE
        WRITE(2,80)'* FCB (FECAL COLIFORM BACTERIA) IS NOT MODELED    '
      ENDIF
C
      IF(IWQSRP.EQ.1)THEN
        WRITE(2,80)'* TAM IS USED FOR SORPTION OF PO4T/SA: MODEL TAM  '
       ELSE IF(IWQSRP.EQ.2)THEN
        WRITE(2,80)'* TSS IS USED FOR SORPTION OF PO4T/SA: MODEL TSS  '
C        IF(ISTRAN(6).NE.1) STOP 'ERROR! INCOMPATIBLE ISTRAN(6)/IWQSRP'
       ELSE
        WRITE(2,80)'* NO SORPTION OF PO4T/SA: MAY MODEL TSS & NO TAM  '
      ENDIF
C
      IF(IWQSTOX.EQ.1)THEN
        WRITE(2,80)'* SALINITY TOXICITY IS APPLIED TO CYANOBACTERIA   '
       ELSE
        WRITE(2,80)'* NO SALINITY TOXICITY: SALTWATER CYANOBACTERIA   '
      ENDIF
C
      IF(IWQKA(1).EQ.0)THEN
        WRITE(2,80)'* USER-SPECIFIED CONSTANT REAERATION SET TO WQKRO '
        WRITE(2,80)'*   REAERATION DUE TO WIND SET TO ZERO            '
      ENDIF
      IF(IWQKA(1).EQ.1)THEN
        WRITE(2,80)'* USER-SPECIFIED CONSTANT REAERATION SET TO WQKRO '
        WRITE(2,80)'*   REAERATION DUE TO WIND ADDED TO WQKRO         '
      ENDIF
      IF(IWQKA(1).EQ.2)THEN
        WRITE(2,80)'* OCONNOR-DOBBINS REAERATION FORMULA IS USED      '
      ENDIF
      IF(IWQKA(1).EQ.3)THEN
        WRITE(2,80)'* OWENS & GIBBS (1964) REAERATION FORMULA IS USED '
      ENDIF
      IF(IWQKA(1).EQ.4)THEN
        WRITE(2,80)'* MODIFIED OWENS & GIBBS REAERATION IS USED       '
      ENDIF
      IF(IWQVLIM.EQ.0)THEN
        WRITE(2,80)'* MACROALGAE GROWTH IS NOT LIMITED BY VELOCITY    '
      ENDIF
      IF(IWQVLIM.EQ.1)THEN
        WRITE(2,80)'* MACROALGAE VELOCITY LIMIT, MICHAELIS-MENTON EQU.'
      ENDIF
      IF(IWQVLIM.EQ.2)THEN
        WRITE(2,80)'* MACROALGAE VEL. LIMIT, 5-PARAM LOGISTIC FUNCTION'
      ENDIF
C
      WRITE(2,83)'* # OF ZONES FOR SPATIALLY VARYING PARAMETERS =',IWQZ
      IF(IWQZ.GT.NWQZ) STOP 'ERROR!! IWQZ SHOULD BE <= NWQZ'
C
      IF(IWQNC.EQ.1)THEN
        WRITE(2,80)'* WRITE NEGATIVE CONC. INFORMATION TO NEG-CONC.LOG'
       ELSE
        WRITE(2,80)'* NO WRTING OF NEGATIVE CONCENTRATION INFORMATION '
      ENDIF
C
      IF(IWQRST.EQ.1)THEN
        WRITE(2,80)'* WRITE SPATIAL DISTRIBUTIONS TO IWQORST          '
       ELSE
        WRITE(2,80)'* NO WRITING TO IWQORST                           '
      ENDIF
C
      WRITE(2,999)
C
      IF(IWQICI.EQ.1)THEN
        WRITE(2,80)'* SPATIALLY/TEMPORALLY-VARYING ICS FROM INWQICI   '
       ELSE IF(IWQICI.EQ.2)THEN
        WRITE(2,80)'* SPATIALLY/TEMPORALLY-VARYING ICS FROM INWQRST   '
       ELSE
        WRITE(2,80)'* SPATIALLY/TEMPORALLY CONSTANT INITIAL CONDITIONS'
      ENDIF
C
      IF(IWQAGR.EQ.1)THEN
        WRITE(2,80)'* SPATIALLY A/O TEMPORALLY-VARYING ALGAL KINETICS '
       ELSE
        WRITE(2,80)'* SPATIALLY/TEMPORALLY CONSTANT ALGAL KINETICS    '
      ENDIF
C
      IF(IWQSTL.EQ.1)THEN
        WRITE(2,80)'* SPATIALLY AND/OR TEMPORALLY-VARYING SETTLING VEL'
       ELSE
        WRITE(2,80)'* SPATIALLY/TEMPORALLY CONSTANT SETTLING VELOCITY '
      ENDIF
C
      IF(IWQSUN.GE.1)THEN
        WRITE(2,80)'* TEMPORALLY-VARYING IO & FD                      '
       ELSE
        WRITE(2,80)'* TEMPORALLY CONSTANT IO & FD                     '
      ENDIF
C
C11_24     IF(IWQPSL.EQ.1)THEN
C11_24        WRITE(2,80)'* TEMPORALLY-VARYING POINT SOURCE INPUT           '
C11_24       ELSE
C11_24        WRITE(2,80)'* TEMPORALLY CONSTANT POINT SOURCE INPUT          '
C11_24      ENDIF
C
      IF(IWQNPL.EQ.1)THEN
        WRITE(2,80)'* SPATIALLY AND/OR TEMPORALLY-VARYING NPS INPUT   '
       ELSE
        WRITE(2,80)'* SPATIALLY/TEMPORALLY CONSTANT NPS INPUT         '
      ENDIF
C
      IF(IWQKIN.EQ.1)THEN
        WRITE(2,80)'* SPATIALLY VARYING KINETICS FROM KINETICS.INP    '
      ELSE
        WRITE(2,80)'* FILE KINETICS.INP NOT USED                      '
      ENDIF
C
C     READ(1,999)
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) IWQTS,TWQTSB,TWQTSE,WQTSDT, ISWQAVG, ISWQMIN, ISWQMAX,
     *          ISCOMP
      WRITE(2,*) IWQTS,TWQTSB,TWQTSE,WQTSDT, ISWQAVG, ISWQMIN, ISWQMAX,
     *          ISCOMP
C ISWQAVG > 0 TURNS ON BINARY FILE OUTPUT FOR WQ DAILY AVERAGES
C ISWQMIN > 0 TURNS ON BINARY FILE OUTPUT FOR WQ DAILY MINIMUMS
C ISWQMAX > 0 TURNS ON BINARY FILE OUTPUT FOR WQ DAILY MAXIMUMS
C ISCOMP  > 0 TURNS ON BINARY FILE OUTPUT FOR DO COMPONENT ANALYSIS
      IF(ISCOMP .GT. 0)THEN
        CALL WQZERO3
        CALL INITBIN3
      ENDIF
C
      IF(IWQTS.GT.NWQTS)THEN
        WRITE(2,80)'** IWQTS SHOULD BE <= NWQTS **                    '
        IWQTS=NWQTS
      ENDIF
C
C
      WRITE(2,84)
     * '* TIME-SERIES OUTPUT FROM ', TWQTSB, ' DAY ',
     * '                       TO ', TWQTSE, ' DAY ',
     * '                    EVERY ', WQTSDT, ' HOUR',
     * '                       AT ', IWQTS,  ' LOCATIONS',
     * ' BIN FILE SWITCH ISWQAVG =', ISWQAVG,' (0=OFF)  ',
     * ' BIN FILE SWITCH ISWQMIN =', ISWQMIN,' (0=OFF)  ',
     * ' BIN FILE SWITCH ISWQMAX =', ISWQMAX,' (0=OFF)  ',
     * ' BIN FILE SWITCH ISCOMP  =', ISCOMP, ' (0=OFF)  '
      WRITE(2,999)
C
C7
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      DO M=1,2
        READ(1,90) TITLE(M)
      ENDDO
      IF(IWQTS.GE.1)THEN
        WRITE(2,80)': ICWQTS(I)=1, TIME-SERIES OUTPUT FOR VARIABLE I  '
        WRITE(2,80)': ICWQTS(I)\=1, NO TIME-SERIES OUTPUT FOR VAR. I  '
        WRITE(2,999)
C
        DO M=1,2
          WRITE(2,90) TITLE(M)
        ENDDO
        DO M=1,IWQTS
          READ(1,*) II,JJ,(ICWQTS(NW,M),NW=1,13)
          WRITE(2,*) II,JJ,(ICWQTS(NW,M),NW=1,13)
          if(IDNOTRVA>0)then
            READ(1,*) (ICWQTS(NW,M),NW=14,NTSWQV),ICWQTS(IDNOTRVA,M)
            WRITE(2,*) (ICWQTS(NW,M),NW=14,NTSWQV),ICWQTS(IDNOTRVA,M)
          else
            READ(1,*) (ICWQTS(NW,M),NW=14,NTSWQV),tmp
            WRITE(2,*) (ICWQTS(NW,M),NW=14,NTSWQV),tmp
          endif
          IF(IJCT(II,JJ).LT.1 .OR. IJCT(II,JJ).GT.8)THEN
            WRITE(2,86)  II,JJ,M
            WRITE(2,80)'ERROR!! INVALID (I,J): TIME-SERIES LOCATION'
            STOP
          ENDIF
          LWQTS(M)=LIJ(II,JJ)
          WRITE(2,94) II,JJ,(ICWQTS(NW,M),NW=1,NTSWQV+1)
        ENDDO
C
      ENDIF
C
      IWQTSB = NINT(TWQTSB/DTD)
      IWQTSE = NINT(TWQTSE/DTD)
      IWQTSDT = NINT(WQTSDT*3600.0/DT)
      WRITE(2,999)
      WRITE(2,83)': TIME-SERIES STARTING TIME STEP (IN DT UNIT) =',
     *  IWQTSB
      WRITE(2,83)': TIME-SERIES ENDING TIME STEP (IN DT UNIT)   =',
     *  IWQTSE
      WRITE(2,83)': FREQUENCY OF TS OUTPUT  (IN DT UNIT)        =',
     *  IWQTSDT
      IF(MOD(IWQTSDT,IWQDT).NE.0)
     *  STOP 'ERROR!! IWQTSDT SHOULD BE MULTIPLE OF IWQDT'
C
  999 FORMAT(1X)
   90 FORMAT(A79)
   91 FORMAT(10I8)
   92 FORMAT(10F8.4)
   93 FORMAT(I8,3F8.4)
   94 FORMAT(2I5, 13I5, /, 10X, 9I5)
   80 FORMAT(A50)
   81 FORMAT(A27, 4(F8.4,2X))
   82 FORMAT((A45, F8.4))
   83 FORMAT(A47, I10)
   84 FORMAT(3(A26,F10.4,A5,/), 5(A26,I8,A10,/))
   86 FORMAT(' I,J,M = ',3I10)
C
C CONSTANT PARAMETERS FOR ALGAE (SEE TABLE 3-1)
C8
C MODIFIED BY J.S.(5/5/98)
C
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQKHNC,WQKHND,WQKHNG,WQKHNM,WQKHPC,WQKHPD,WQKHPG,
     1 WQKHPM,WQKHS,WQSTOX
      WRITE(2,*) WQKHNC,WQKHND,WQKHNG,WQKHNM,WQKHPC,WQKHPD,WQKHPG,
     1  WQKHPM,WQKHS,WQSTOX
      WRITE(2,80)'* HALF-SAT. COSNTANT (G/M^3) FOR NUTRIENT UPTAKE  '
      WRITE(2,81)' : (KHNC, KHPC)          = ', WQKHNC,WQKHPC
      WRITE(2,81)' : (KHND, KHPD, KHS)     = ', WQKHND,WQKHPD,WQKHS
      WRITE(2,81)' : (KHNG, KHPG)          = ', WQKHND,WQKHPG
      WRITE(2,81)' : (KHNM, KHPM)          = ', WQKHNM,WQKHPM
      WRITE(2,82)'* SAL. WHERE MICROSYSTIS GROWTH IS HALVED  = ',
     &        WQSTOX
      WQSTOX = WQSTOX*WQSTOX
C9
C    MODIFIED BY J.S.(5/5/98)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQKETSS,WQKECHL,WQCHLC,WQCHLD,WQCHLG,WQCHLM,WQDOPC,
     * WQDOPD,WQDOPG, WQDOPM(1)
      WRITE(2,*) WQKETSS,WQKECHL,WQCHLC,WQCHLD,WQCHLG,WQCHLM,WQDOPC,
     * WQDOPD,WQDOPG, WQDOPM(1)
C
      IF(ISTRAN(6).NE.1)THEN
        WQKETSS=0.0
        WRITE(2,80)': SINCE TSS IS NOT MODELED, KETSS IS FORCED TO 0  '
      ENDIF
C
      WRITE(2,80)'* LIGHT EXTINC. COEFF. DUE TO TSS & CHL           '
      WRITE(2,81)' : KETSS (/M PER G/M^3)  = ', WQKETSS
      WRITE(2,81)' : KECHL (/M PER MG/M^3) = ', WQKECHL
      IF(WQKECHL .LT. 0.0)THEN
        WRITE(2,80) '* USE RILEY (1956) EQUATION FOR WQKECHL          '
        WRITE(2,80) ' : KECHL = 0.054*CHL**0.667 + 0.0088*CHL         '
      ENDIF
      WRITE(2,80)'* CARBON-TO-CHL RATIO (G C PER MG CHL)            '
      WRITE(2,81)' : (CCHLC, CCHLD, CCHLG) = ', WQCHLC,WQCHLD,WQCHLG
      WRITE(2,80)'* DEPTH (M) OF MAXIMUM ALGAL GROWTH               '
      WRITE(2,81)' : (DOPTC, DOPTD, DOPTG) = ', WQDOPC,WQDOPD,WQDOPG
      WQCHLC=1.0/(WQCHLC+ 1.E-12)
      WQCHLD=1.0/(WQCHLD+ 1.E-12)
      WQCHLG=1.0/(WQCHLG+ 1.E-12)
      WQCHLM=1.0/(WQCHLM+ 1.E-12)
C10
C    MODIFIED BY J.S. (5/5/98)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQI0,WQISMIN,WQFD,WQCIA,WQCIB,WQCIC,WQCIM,REAC(1),
     &         PARADJ, SIceAdj
      WRITE(2,*) WQI0,WQISMIN,WQFD,WQCIA,WQCIB,WQCIC,WQCIM,REAC(1),
     &         PARADJ
      WRITE(2,82)'*INITIAL IO (LY/D) AT WATER SURFACE       = ',WQI0
     *          ,' MINIMUM OPTIMUM SOLAR RADIATION (LY/D)   = ',WQISMIN
     *          ,' FRACTIONAL DAYLENGTH                     = ',WQFD
     *          ,' WEIGHTING FACTOR FOR RAD. AT CURRENT DAY = ',WQCIA
     *          ,' WEIGHTING FACTOR FOR RAD. AT (-1) DAY    = ',WQCIB
     *          ,' WEIGHTING FACTOR FOR RAD. AT (-2) DAYS   = ',WQCIC
     *          ,' FRACTION OF SOLAR RADIATION THAT IS PAR  = ',PARADJ
      WQI1 = WQI0
      WQI2 = WQI0
      WQI3 = WQI0
      WQI0OPT = 0.0
      IF(IWQSUN .EQ. 2)THEN
        DO L=2,LA
	   WQIH0OPT(L)=0
	   WQIH3(L) = WQI0
         WQIH2(L) = WQI0
         WQIH1(L) = WQI0
        ENDDO
        WQISMIN = 0.0
      ENDIF
C
C      READ(1,999)
C      READ(1,*) WQTMC,WQTMD,WQTMG,WQKG1C,WQKG2C,WQKG1D,WQKG2D,WQKG1G,
C     *  WQKG2G
C      WRITE(2,80)'* OPTIMUM TEMPERATURE FOR ALGAL GROWTH (DEGC)     '
C      WRITE(2,81)' : (TMC, TMD, TMG      ) = ', WQTMC,WQTMD,WQTMG
C      WRITE(2,80)'* SUBOPTIMAL TEMPERATURE EFFECT FOR ALGAL GROWTH  '
C      WRITE(2,81)' : (KTG1C, KTG1D, KTG1G) = ', WQKG1C,WQKG1D,WQKG1G
C      WRITE(2,80)'* SUPEROPTIMAL TEMPERATURE EFFECT FOR ALGAL GROWTH'
C      WRITE(2,81)' : (KTG2C, KTG2D, KTG2G) = ', WQKG2C,WQKG2D,WQKG2G
C MODIFIED ON 03/05/97 BY JMH/MRM:
C11 MODIFIED BY J.S.(5/5/98)
C
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*)WQTMC1,WQTMC2,WQTMD1,WQTMD2,WQTMG1,WQTMG2,WQTMM1,WQTMM2,
     &         WQTMP1, WQTMP2
      WRITE(2,*)WQTMC1,WQTMC2,WQTMD1,WQTMD2,WQTMG1,WQTMG2,WQTMM1,
     &         WQTMM2,WQTMP1, WQTMP2
C12
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*)WQKG1C,WQKG2C,WQKG1D,WQKG2D,WQKG1G,WQKG2G,WQKG1M,WQKG2M,
     &         WQKG1P, WQKG2P
      WRITE(2,*)WQKG1C,WQKG2C,WQKG1D,WQKG2D,WQKG1G,WQKG2G,WQKG1M,
     &         WQKG2M,WQKG1P, WQKG2P
      WRITE(2,80)'* LOWER OPTIMUM TEMP FOR ALGAL GROWTH (DEGC)     '
      WRITE(2,81)' : (TMC1, TMD1, TMG1   ) = ', WQTMC1,WQTMD1,WQTMG1
      WRITE(2,80)'* UPPER OPTIMUM TEMP FOR ALGAL GROWTH (DEGC)     '
      WRITE(2,81)' : (TMC2, TMD2, TMG2   ) = ', WQTMC2,WQTMD2,WQTMG2
C13
C   MODIFIED BY J.S.(5/5/98)
C
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQTRC,WQTRD,WQTRG,WQTRM,WQKTBC,WQKTBD,WQKTBG,WQKTBM
      WRITE(2,*) WQTRC,WQTRD,WQTRG,WQTRM,WQKTBC,WQKTBD,WQKTBG,WQKTBM
      WRITE(2,80)'* REFERENCE TEMPERATURE FOR ALGAL METABOLISM (OC) '
      WRITE(2,81)' : (TRC, TRD, TRG)       = ', WQTRC,WQTRD,WQTRG
      WRITE(2,80)'* TEMPERATURE EFFECT FOR ALGAL METABOLISM         '
      WRITE(2,81)' : (KTBC, KTBD, KTBG)    = ', WQKTBC,WQKTBD,WQKTBG
C
C CONSTANT PARAMETERS FOR CARBON (SEE TABLE 3-2)
C
C14
C   MODIFIED BY J.S.(5/5/98)
C
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQFCRP,WQFCLP,WQFCDP,WQFCDC,WQFCDD,WQFCDG,
     * WQKHRC,WQKHRD,WQKHRG
      WRITE(2,*) WQFCRP,WQFCLP,WQFCDP,WQFCDC,WQFCDD,WQFCDG,
     * WQKHRC,WQKHRD,WQKHRG
      WRITE(2,80)'* CARBON DISTRIBUTION COEFF FOR ALGAL PREDATION   '
      WRITE(2,81)' : (FCRP, FCLP, FCDP)    = ', WQFCRP,WQFCLP,WQFCDP
      WRITE(2,80)'* CARBON DISTRIBUTION COEFF FOR ALGAL METABOLISM  '
      WRITE(2,81)' : (FCDC, FCDD, FCDG)    = ', WQFCDC,WQFCDD,WQFCDG
      WRITE(2,80)'* HALF-SAT. CONSTANT (GO/M*3) FOR ALGAL DOC EXCRET'
      WRITE(2,81)' : (KHRC, KHRD, KHRG)    = ', WQKHRC,WQKHRD,WQKHRG
      CFCDCWQ = 1.0 - WQFCDC
      CFCDDWQ = 1.0 - WQFCDD
      CFCDGWQ = 1.0 - WQFCDG
      XC = ABS(1.0 - (WQFCRP+WQFCLP+WQFCDP))
      IF(XC .GT. 0.0001)THEN
        WRITE(2,*)
        WRITE(2,*) ' WARNING!  FCRP+FCLP+FCDP NOT EQUAL TO 1.0'
        WRITE(2,*)
      ENDIF
C   MODIFIED BY J.S.(5/5/98)
C
C15 
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQFCRPM,WQFCLPM,WQFCDPM,WQFCDM, WQKHRM(1)
      WRITE(2,*) WQFCRPM,WQFCLPM,WQFCDPM,WQFCDM, WQKHRM(1)
C16
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*)WQKRC,WQKLC,WQKDC(1),WQKRCALG,WQKLCALG,WQKDCALG,
     *         WQKDCALM(1)
      WRITE(2,*)WQKRC,WQKLC,WQKDC(1),WQKRCALG,WQKLCALG,WQKDCALG,
     *         WQKDCALM(1)
      WRITE(2,80)'* MINIMUM DISSOLUTION RATE (/DAY) OF ORGANIC C    '
      WRITE(2,81)' : (KRC, KLC, KDC)       = ', WQKRC,WQKLC,WQKDC(1)
      WRITE(2,80)'* CONSTANT RELATING DISSOLUTION RATE TO ALGAE     '
      WRITE(2,81)' : (KRCALG,KLCALG,KDCALG)= ', WQKRCALG,WQKLCALG,
     *  WQKDCALG
C17
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQTRHDR,WQTRMNL,WQKTHDR,WQKTMNL,WQKHORDO,WQKHDNN,
     *  WQAANOX
      WRITE(2,*) WQTRHDR,WQTRMNL,WQKTHDR,WQKTMNL,WQKHORDO,WQKHDNN,
     *  WQAANOX
      WRITE(2,80)'* REFERENCE TEMP FOR HYDROLYSIS/MINERALIZATION(OC)'
      WRITE(2,81)' : (TRHDR, TRMNL)        = ', WQTRHDR,WQTRMNL
      WRITE(2,80)'* TEMPERATURE EFFECT ON HYDROLYSIS/MINERALIZATION '
      WRITE(2,81)' : (KTHDR, KTMNL)        = ', WQKTHDR,WQKTMNL
      WRITE(2,80)'* HALF-SAT. CONSTANT FOR OXIC RESP/DENITRIFICATION'
      WRITE(2,81)' : (KHORDO, KHDNN)       = ', WQKHORDO,WQKHDNN
      WRITE(2,80)'* RATION OF DENITRIFICATION TO OXIC DOC RESP      '
      WRITE(2,81)' : (AANOX)               = ', WQAANOX
      WQAANOX = WQAANOX*WQKHORDO
C
C CONSTANT PARAMETERS FOR PHOSPHORUS (TABLE 3-3)
C
C18
C   MODIFIED BY J.S.(5/5/98)
C
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQFPRP,WQFPLP,WQFPDP,WQFPIP,WQFPRC,WQFPRD,WQFPRG,
     * WQFPLC,WQFPLD,WQFPLG
      WRITE(2,*) WQFPRP,WQFPLP,WQFPDP,WQFPIP,WQFPRC,WQFPRD,WQFPRG,
     * WQFPLC,WQFPLD,WQFPLG
      WRITE(2,80)'* PHOSPHORUS DISTRIBUTION COEF FOR ALGAL PREDATION'
      WRITE(2,81)' : (FPRP,FPLP,FPDP,FPIP) = ', WQFPRP,WQFPLP,WQFPDP,
     *  WQFPIP
      WRITE(2,80)'* PHOSPHORUS DIST COEF OF RPOP FOR ALGAL METABOLIS'
      WRITE(2,81)' : (FPRC, FPRD, FPRG)    = ', WQFPRC,WQFPRD,WQFPRG
      WRITE(2,80)'* PHOSPHORUS DIST COEF OF LPOP FOR ALGAL METABOLIS'
      WRITE(2,81)' : (FPLC, FPLD, FPLG)    = ', WQFPLC,WQFPLD,WQFPLG
      XP = ABS(1.0 - (WQFPRP+WQFPLP+WQFPDP+WQFPIP))
      IF(XP .GT. 0.0001)THEN
        WRITE(2,*)
        WRITE(2,*) ' WARNING!  FPRP+FPLP+FPDP+FPIP NOT EQUAL TO 1.0'
        WRITE(2,*)
      ENDIF
C19
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*)WQFPRPM,WQFPLPM,WQFPDPM,WQFPIPM,WQFPRM,WQFPLM,WQAPCM
      WRITE(2,*)WQFPRPM,WQFPLPM,WQFPDPM,WQFPIPM,WQFPRM,WQFPLM,WQAPCM
C
C20
C   MODIFIED BY J.S.(5/5/98)
C
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQFPDC,WQFPDD,WQFPDG,WQFPDM,WQFPIC,WQFPID,WQFPIG,
     * WQFPIM,WQKPO4P
      WRITE(2,*) WQFPDC,WQFPDD,WQFPDG,WQFPDM,WQFPIC,WQFPID,WQFPIG,
     * WQFPIM,WQKPO4P
      IF(IWQSRP.NE.1 .AND. IWQSRP.NE.2)THEN
        WQKPO4P = 0.0
        WRITE(2,80)': NO SORPTION OF PO4T/SA, SO KPO4P IS FORCED TO 0 '
      ENDIF
      WRITE(2,80)'* PHOSPHORUS DIST COEF OF DOP FOR ALGAL METABOLISM'
      WRITE(2,81)' : (FPDC, FPDD, FPDG)    = ', WQFPDC,WQFPDD,WQFPDG
      WRITE(2,80)'* PHOSPHORUS DIST COEF OF NH4 FOR ALGAL METABOLISM'
      WRITE(2,81)' : (FPIC, FPID, FPIG)    = ', WQFPIC,WQFPID,WQFPIG
      WRITE(2,82)'* PARITITION COEFF FOR SORBED/DISSOLVED PO4 =',
     &             WQKPO4P
      XPC = ABS(1.0 - (WQFPRC+WQFPLC+WQFPDC+WQFPIC))
      IF(XPC .GT. 0.0001)THEN
        WRITE(2,*)
        WRITE(2,*) ' WARNING!  FPRC+FPLC+FPDC+FPIC NOT EQUAL TO 1.0'
        WRITE(2,*)
      ENDIF
      XPD = ABS(1.0 - (WQFPRD+WQFPLD+WQFPDD+WQFPID))
      IF(XPD .GT. 0.0001)THEN
        WRITE(2,*)
        WRITE(2,*) ' WARNING!  FPRD+FPLD+FPDD+FPID NOT EQUAL TO 1.0'
        WRITE(2,*)
      ENDIF
      XPG = ABS(1.0 - (WQFPRG+WQFPLG+WQFPDG+WQFPIG))
      IF(XPG .GT. 0.0001)THEN
        WRITE(2,*)
        WRITE(2,*) ' WARNING!  FPRG+FPLG+FPDG+FPIG NOT EQUAL TO 1.0'
        WRITE(2,*)
      ENDIF
C21

      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQKRP,WQKLP,WQKDP,WQKRPALG,WQKLPALG,WQKDPALG,WQCP1PRM,
     *  WQCP2PRM,WQCP3PRM
      WRITE(2,*) WQKRP,WQKLP,WQKDP,WQKRPALG,WQKLPALG,WQKDPALG,WQCP1PRM,
     *  WQCP2PRM,WQCP3PRM
      WRITE(2,80)'* MINIMUM HYDROLYSIS RATE (/DAY) OF ORGANIC P     '
      WRITE(2,81)' : (KRP, KLP, KDP)       = ', WQKRP,WQKLP,WQKDP
      WRITE(2,80)'* CONSTANT RELATING HYDROLYSIS RATE TO ALGAE      '
      WRITE(2,81)' : (KRPALG,KLPALG,KDPALG)= ', WQKRPALG,WQKLPALG,
     *  WQKDPALG
      WRITE(2,80)'* CONSTANT USED IN DETERMINING P-TO-C RATIO       '
      WRITE(2,81)' : (CPPRM1,CPPRM2,CPPRM3)= ', WQCP1PRM,WQCP2PRM,
     *  WQCP3PRM
C
C CONSTANT PARAMETERS FOR NITROGEN (TABLE 3-4)
C
C22
C   MODIFIED BY J.S.(5/5/98)
C
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQFNRP,WQFNLP,WQFNDP,WQFNIP,WQFNRC,WQFNRD,WQFNRG,
     *  WQFNLC,WQFNLD,WQFNLG
      WRITE(2,*) WQFNRP,WQFNLP,WQFNDP,WQFNIP,WQFNRC,WQFNRD,WQFNRG,
     *  WQFNLC,WQFNLD,WQFNLG
      WRITE(2,80)'* NITROGEN DISTRIBUTION COEFF FOR ALGAL PREDATION '
      WRITE(2,81)' : (FNRP,FNLP,FNDP,FNIP) = ', WQFNRP,WQFNLP,WQFNDP,
     *  WQFNIP
      WRITE(2,80)'* NITROGEN DIST COEF OF RPON FOR ALGAL METABOLISM '
      WRITE(2,81)' : (FNRC, FNRD, FNRG)    = ', WQFNRC,WQFNRD,WQFNRG
      WRITE(2,80)'* NITROGEN DIST COEF OF LPON FOR ALGAL METABOLISM '
      WRITE(2,81)' : (FNLC, FNLD, FNLG)    = ', WQFNLC,WQFNLD,WQFNLG
      XN = ABS(1.0 - (WQFNRP+WQFNLP+WQFNDP+WQFNIP))
      IF(XN .GT. 0.0001)THEN
        WRITE(2,*)
        WRITE(2,*) ' WARNING!  FNRP+FNLP+FNDP+FNIP NOT EQUAL TO 1.0'
        WRITE(2,*)
      ENDIF
C23
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*)WQFNRPM,WQFNLPM,WQFNDPM,WQFNIPM,WQFNRM,WQFNLM
      WRITE(2,*)WQFNRPM,WQFNLPM,WQFNDPM,WQFNIPM,WQFNRM,WQFNLM
C24
C   MODIFIED BY J.S.(5/5/98)
C
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQFNDC,WQFNDD,WQFNDG,WQFNDM,WQFNIC,WQFNID,WQFNIG,
     * WQFNIM,WQANCC,WQANCD,WQANCG,WQANCM
      WRITE(2,*) WQFNDC,WQFNDD,WQFNDG,WQFNDM,WQFNIC,WQFNID,WQFNIG,
     * WQFNIM,WQANCC,WQANCD,WQANCG,WQANCM
      WRITE(2,80)'* NITROGEN DIST COEF OF DON FOR ALGAL METABOLISM  '
      WRITE(2,81)' : (FNDC, FNDD, FNDG)    = ', WQFNDC,WQFNDD,WQFNDG
      WRITE(2,80)'* NITROGEN DIST COEF OF NH4 FOR ALGAL METABOLISM  '
      WRITE(2,81)' : (FNIC, FNID, FNIG)    = ', WQFNIC,WQFNID,WQFNIG
      WRITE(2,80)'* NITROGEN-TO-CARBON RATIO IN ALGAE               '
      WRITE(2,81)' : (ANCC, ANCD, ANCG)    = ', WQANCC,WQANCD,WQANCG
      XNC = ABS(1.0 - (WQFNRC+WQFNLC+WQFNDC+WQFNIC))
      IF(XNC .GT. 0.0001)THEN
        WRITE(2,*)
        WRITE(2,*) ' WARNING!  FNRC+FNLC+FNDC+FNIC NOT EQUAL TO 1.0'
        WRITE(2,*)
      ENDIF
      XND = ABS(1.0 - (WQFNRD+WQFNLD+WQFNDD+WQFNID))
      IF(XND .GT. 0.0001)THEN
        WRITE(2,*)
        WRITE(2,*) ' WARNING!  FNRD+FNLD+FNDD+FNID NOT EQUAL TO 1.0'
        WRITE(2,*)
      ENDIF
      XNG = ABS(1.0 - (WQFNRG+WQFNLG+WQFNDG+WQFNIG))
      IF(XNG .GT. 0.0001)THEN
        WRITE(2,*)
        WRITE(2,*) ' WARNING!  FNRG+FNLG+FNDG+FNIG NOT EQUAL TO 1.0'
        WRITE(2,*)
      ENDIF
C
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQANDC,WQNITM,WQKHNDO,WQKHNN,WQTNIT,WQKN1,WQKN2
      WRITE(2,*) WQANDC,WQNITM,WQKHNDO,WQKHNN,WQTNIT,WQKN1,WQKN2
      WRITE(2,82)'* MASS NO3 REDUCED PER DOC OXIDIZED (GN/GC)= ',WQANDC
     *          ,'* MAXIMUM NITRIFICATION RATE (G N /M^3/D)  = ',WQNITM
     *          ,'  REFERENCE TEMP FOR NITRIFICATION (DEGC)  = ',WQTNIT
      WRITE(2,80)'* NITRIFICATION HALF-SAT CONSTANT FOR DO & NH4    '
      WRITE(2,81)' : (KHNITDO, KHNITN)     = ', WQKHNDO,WQKHNN
      WRITE(2,80)'* SUB & SUPER-OPTIMUM TEMP EFFECT ON NITRIFICATION'
      WRITE(2,81)' : (KNIT1, KNIT2)        = ', WQKN1,WQKN2
C
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQKRN,WQKLN,WQKDN,WQKRNALG,WQKLNALG,WQKDNALG
      WRITE(2,*) WQKRN,WQKLN,WQKDN,WQKRNALG,WQKLNALG,WQKDNALG
      WRITE(2,80)'* MINIMUM HYDROLYSIS RATE (/DAY) OF ORGANIC N     '
      WRITE(2,81)' : (KRN, KLN, KDN)       = ', WQKRN,WQKLN,WQKDN
      WRITE(2,80)'* CONSTANT RELATING HYDROLYSIS RATE TO ALGAE      '
      WRITE(2,81)' : (KRNALG,KLNALG,KDNALG)= ', WQKRNALG,WQKLNALG,
     *  WQKDNALG
C
C CONSTANT PARAMETERS FOR SILICA (TABLE 3-5)
C
C     READ(1,999)
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQFSPP,WQFSIP,WQFSPD,WQFSID,WQASCD,WQKSAP,WQKSU,
     *  WQTRSUA,WQKTSUA
      WRITE(2,*) WQFSPP,WQFSIP,WQFSPD,WQFSID,WQASCD,WQKSAP,WQKSU,
     *  WQTRSUA,WQKTSUA
      IF(IWQSRP.NE.1 .AND. IWQSRP.NE.2)THEN
        WQKSAP = 0.0
        WRITE(2,80)': NO SORPTION OF PO4T/SA, SO KSAP IS FORCED TO 0  '
      ENDIF
      WRITE(2,80)'* SILICA DISTRIBUTION COEFF FOR DIATOM PREDATION  '
      WRITE(2,81)' : (FSPP, FSIP)          = ', WQFSPP,WQFSIP
      WRITE(2,80)'* SILICA DISTRIBUTION COEFF FOR DIATOM METABOLISM '
      WRITE(2,81)' : (FSPD, FSID)          = ', WQFSPD,WQFSID
      WRITE(2,82)'*SILICA-TO-CARBON RATIO IN DIATOMS        = ',WQASCD
     *          ,'*PARITITION COEFF FOR SORBED/DISSOLVED SA = ',WQKSAP
     *          ,'*DISSOLUTION RATE (/D) OF PSI             = ',WQKSU
     *          ,' REFERENCE TEMP FOR PSI DISSOLUTION (OC)  = ',WQTRSUA
     *          ,' TEMPERATURE EFFECT ON PSI DISSOLUTION    = ',WQKTSUA
CXH   IF(WQFSPP+WQFSIP.NE.1.0) STOP 'ERROR!! INVALID FSPP,FSIP VALUES'
CXH   IF(WQFSPD+WQFSID.NE.1.0) STOP 'ERROR!! INVALID FSPD,FSID VALUES'
C
C CONSTANT PARAMETERS FOR COD & DO (TABLE 3-6)
C
C     READ(1,999)
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQAOCR,WQAONT, WQKRO(1), WQKTR(1),WQKHCOD(1),WQKCD(1),
     * WQTRCOD, WQKTCOD, WQAOCRPM, WQAOCRRM
      WRITE(2,*) WQAOCR,WQAONT, WQKRO(1), WQKTR(1),WQKHCOD(1),WQKCD(1),
     * WQTRCOD, WQKTCOD, WQAOCRPM, WQAOCRRM
      WRITE(2,82)'* DO-TO-CARBON RATIO IN RESPIRATION        = ',WQAOCR
     *       ,':MASS DO CONSUMED PER NH4-N NITRIFIED     = ',WQAONT
     *       ,':PROPORN. CONSTANT FOR DO-REAERATION (MKS)= ',WQKRO(1)
     *       ,' TEMPERATURE EFFECT ON DO-REAERATION      = ',WQKTR(1)
     *       ,'*HALF-SAT CONSTANT OF DO FOR COD (GO2/M^3)= ',WQKHCOD(1)
     *       ,':OXIDATION RATE OF COD (/DAY)             = ',WQKCD(1)
     *       ,'  REFERENCE TEMP FOR COD OXIDATION (OC)    = ',WQTRCOD
     *       ,'  TEMPERATURE EFFECT ON COD OXIDATION      = ',WQKTCOD
     *       ,': DO-TO-CARBON RATIO MACROALGAE PHOTOSYNTH = ',WQAOCRPM
     *       ,': DO-TO-CARBON RATIO MACROALGAE RESPIRATION= ',WQAOCRRM
C
C CONSTANT PARAMETERS FOR TAM & FCB (TABLE 3-7)
C
C     READ(1,999)
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQKHBMF,WQBFTAM,WQTTAM,WQKTAM,WQTAMDMX,WQKDOTAM,
     *  WQKFCB,WQTFCB
      WRITE(2,*) WQKHBMF,WQBFTAM,WQTTAM,WQKTAM,WQTAMDMX,WQKDOTAM,
     *  WQKFCB,WQTFCB
      WRITE(2,82)
     *  '* DO WHERE TAM RELEASE IS HALF ANOXIC ONE  = ',WQKHBMF
     * ,'  ANOXIC RELEASE OF TAM (MOL/M^2/D)        = ',WQBFTAM
     * ,'  REFERENCE TEMP FOR TAM RELEASE (OC)      = ',WQTTAM
     * ,'  TEMPERATURE EFFECT ON TAM RELEASE        = ',WQKTAM
     * ,': TAM SOLUBILITY AT ANOXIC COND. (MOL/M^3) = ',WQTAMDMX
     * ,'  CONSTANT RELATING TAM SOLUBILITY TO DO   = ',WQKDOTAM
     * ,'* FIRST-ORDER DIE-OFF RATE AT 20OC (/D)    = ',WQKFCB
     * ,'  TEMPERATURE EFFECT ON BACTERIA DIE-OFF   = ',WQTFCB
C
C SET UP LOOK-UP TABLE FOR TEMPERATURE DEPENDENCY OVER -15OC TO 40OC
C

      DO M=1,NWQTD
C        WTEMP =1.00*REAL(M-1)*0.5 - 4.95
c -charles       WTEMP =1.00*REAL(M-1)*0.1 - 14.95
        WTEMP =0.25*REAL(M)-30.25
C       WTEMP =1.23*REAL(M-1)*0.1 - 14.95
C       WTEMP =1.4*REAL(M-1)*0.1 - 4.95
C       WTEMP =REAL(M-1)*0.1 - 4.95
C
C        IF(WTEMP.GT.WQTMC)THEN
C          WQTDGC(M) = EXP( WQKG1C*(WTEMP-WQTMC)*(WQTMC-WTEMP) )
C         ELSE
C          WQTDGC(M) = EXP( WQKG2C*(WTEMP-WQTMC)*(WQTMC-WTEMP) )
C        ENDIF
C
C        IF(WTEMP.GT.WQTMD)THEN
C          WQTDGD(M) = EXP( WQKG1D*(WTEMP-WQTMD)*(WQTMD-WTEMP) )
C         ELSE
C          WQTDGD(M) = EXP( WQKG2D*(WTEMP-WQTMD)*(WQTMD-WTEMP) )
C        ENDIF
C
C        IF(WTEMP.GT.WQTMG)THEN
C          WQTDGG(M) = EXP( WQKG1G*(WTEMP-WQTMG)*(WQTMG-WTEMP) )
C         ELSE
C          WQTDGG(M) = EXP( WQKG2G*(WTEMP-WQTMG)*(WQTMG-WTEMP) )
C        ENDIF
C MODIFIED ON 03/04/96 BY JMH/MRM:
        WQTDGC(M)=1.
        IF(WTEMP.LT.WQTMC1)THEN
          WQTDGC(M) = EXP(-WQKG1C*(WTEMP-WQTMC1)*(WTEMP-WQTMC1) )
        ENDIF
        IF(WTEMP.GT.WQTMC2)THEN
          WQTDGC(M) = EXP(-WQKG2C*(WTEMP-WQTMC2)*(WTEMP-WQTMC2) )
        ENDIF
C
        WQTDGD(M)=1.
        IF(WTEMP.LT.WQTMD1)THEN
          WQTDGD(M) = EXP(-WQKG1D*(WTEMP-WQTMD1)*(WTEMP-WQTMD1) )
        ENDIF
        IF(WTEMP.GT.WQTMD2)THEN
          WQTDGD(M) = EXP(-WQKG2D*(WTEMP-WQTMD2)*(WTEMP-WQTMD2) )
        ENDIF
C
        WQTDGG(M)=1.
        IF(WTEMP.LT.WQTMG1)THEN
          WQTDGG(M) = EXP(-WQKG1G*(WTEMP-WQTMG1)*(WTEMP-WQTMG1) )
        ENDIF
        IF(WTEMP.GT.WQTMG2)THEN
          WQTDGG(M) = EXP(-WQKG2G*(WTEMP-WQTMG2)*(WTEMP-WQTMG2) )
        ENDIF
C J.S.  5/5/98
        WQTDGM(M)=1.
        IF(IDNOTRVA.GT.0)THEN
          IF(WTEMP.LT.WQTMM1)THEN
            WQTDGM(M) = EXP(-WQKG1M*(WTEMP-WQTMM1)*(WTEMP-WQTMM1) )
          ENDIF
          IF(WTEMP.GT.WQTMM2)THEN
            WQTDGM(M) = EXP(-WQKG2M*(WTEMP-WQTMM2)*(WTEMP-WQTMM2) )
          ENDIF
          WQTDRM(M) = EXP( WQKTBM*(WTEMP-WQTRM) )
        ENDIF
C J.S.
C MRM: 06/20/98
C  THE FOLLOWING WQTDGP VARIABLE IS A TEMPERATURE RELATED ADJUSTMENT
C  TO THE PREDATION AND/OR BASAL MATABOLISM RATE TO ALLOW DIATOMS
C  TO BLOOM IN WINTER (OR OTHER TIME OF YEAR).
        WQTDGP(M)=1.
        IF(WTEMP.LT.WQTMP1)THEN
          WQTDGP(M) = EXP(-WQKG1P*(WTEMP-WQTMP1)*(WTEMP-WQTMP1) )
        ENDIF
        IF(WTEMP.GT.WQTMD2)THEN
          WQTDGP(M) = EXP(-WQKG2P*(WTEMP-WQTMP2)*(WTEMP-WQTMP2) )
        ENDIF
C MRM
C
C        WRITE(1,555)WTEMP,WQTDGC(M),WQTDGD(M),WQTDGG(M),WQTDGM(M)
555     FORMAT(F7.2,4E12.4)
        WQTDRC(M) = EXP( WQKTBC*(WTEMP-WQTRC) )
        WQTDRD(M) = EXP( WQKTBD*(WTEMP-WQTRD) )
        WQTDRG(M) = EXP( WQKTBG*(WTEMP-WQTRG) )
        WQTDHDR(M) = EXP( WQKTHDR*(WTEMP-WQTRHDR) )
        WQTDMNL(M) = EXP( WQKTMNL*(WTEMP-WQTRMNL) )
C
        IF(WTEMP.GT.WQTNIT)THEN
          WQTDNIT(M)=WQNITM*EXP( WQKN1*(WTEMP-WQTNIT)*(WQTNIT-WTEMP) )
         ELSE
          WQTDNIT(M)=WQNITM*EXP( WQKN2*(WTEMP-WQTNIT)*(WQTNIT-WTEMP) )
        ENDIF
C
        WQKSUA(M) = WQKSU * EXP( WQKTSUA*(WTEMP-WQTRSUA) )
        WQKCOD(M,1) = WQKCD(1) * EXP( WQKTCOD*(WTEMP-WQTRCOD) )
        TT20 = WTEMP-20.0
        WQTDKR(M,1) = WQKTR(1)**TT20
            WRITE(2,2222)M,WQKTR(1),WQTDKR(M,1)
        WQTDTAM(M) = WQKHBMF * WQBFTAM * EXP( WQKTAM*(WTEMP-WQTTAM) )
        WQTT = WQKFCB * WQTFCB**TT20 * DTWQO2
        WQTD1FCB(M) = 1.0 - WQTT
        WQTD2FCB(M) = 1.0 / (1.0 + WQTT)
        ENDDO
C
C READ SECOND PART: RWQC2
C PARAMETERS FOR WATER QUALITY STATE VARIABLE TIME SERIES
C
C
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
        DO M=1,5
          READ(1,90) TITLE(M)
          WRITE(2,90) TITLE(M)
        ENDDO
      READ(1,*) (NWQCSR(NW),NW=1,NWQV)
      WRITE(2,*) (NWQCSR(NW),NW=1,NWQV)
      WRITE(2,970)(NWQCSR(NW),NW=1,NWQV)
C
C
C READ SECOND PART: RWQC2
C PARAMETERS FOR OPEN BOUNDARY CONDITIONS
C
C     READ(1,999)
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) NWQOBS,NWQOBW,NWQOBE,NWQOBN
      WRITE(2,*) NWQOBS,NWQOBW,NWQOBE,NWQOBN
      WRITE(2,23)'* # OF OPEN BDRY CELLS ON SOUTH BDRY       = ',NWQOBS
      WRITE(2,23)'* # OF OPEN BDRY CELLS ON WEST BDRY        = ',NWQOBW
      WRITE(2,23)'* # OF OPEN BDRY CELLS ON EAST BDRY        = ',NWQOBE
      WRITE(2,23)'* # OF OPEN BDRY CELLS ON NORTH BDRY       = ',NWQOBN
      IF(NWQOBS.GT.NBBSM) STOP 'ERROR!! NWQOBS SHOULD <= NBBSM'
      IF(NWQOBW.GT.NBBWM) STOP 'ERROR!! NWQOBW SHOULD <= NBBWM'
      IF(NWQOBE.GT.NBBEM) STOP 'ERROR!! NWQOBE SHOULD <= NBBEM'
      IF(NWQOBN.GT.NBBNM) STOP 'ERROR!! NWQOBN SHOULD <= NBBNM'
C      IF(NWQOBS.NE.NCBS) STOP 'ERROR!! NWQOBS =\ NCBS'
C      IF(NWQOBW.NE.NCBW) STOP 'ERROR!! NWQOBW =\ NCBW'
C      IF(NWQOBE.NE.NCBE) STOP 'ERROR!! NWQOBE =\ NCBE'
C      IF(NWQOBN.NE.NCBN) STOP 'ERROR!! NWQOBN =\ NCBN'
      WRITE(2,999)
C      WRITE(2,80)'* NOTE THAT THE ORDER OF OB CELLS BELOW SHOULD BE '
C     WRITE(2,80)'  THE SAME AS THAT IN HYM, IWQCBS=ICBS,JWQCBS=JCBS'
      WRITE(2,80)'* CONSTANT OBC AT (ICBX(M),JCBX(M)) IF IWQOBX(M)=0'
      WRITE(2,80)': READ TIME-SERIES OBCS IWQOBX TIMES IF IWQOBX > 0'
C
C SOUTH BDRY
C
C      DO M=1,2
C       READ(1,90) TITLE(M)
C       WRITE(2,90) TITLE(M)
C     ENDDO
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
        DO M=1,5
          READ(1,90) TITLE(M)
          WRITE(2,90) TITLE(M)
        ENDDO
      IF(NWQOBS.GT.0)THEN
        DO M=1,NWQOBS
          READ(1,*) IWQCBS(M),JWQCBS(M),(IWQOBS(M,NW),NW=1,NWQV)
          WRITE(2,*) IWQCBS(M),JWQCBS(M),(IWQOBS(M,NW),NW=1,NWQV)
          WRITE(2,969) IWQCBS(M),JWQCBS(M),(IWQOBS(M,NW),NW=1,NWQV)
        ENDDO
      ENDIF
C
C: CONSTANT BOTTOM AND SURFACE OBCS
C
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
        DO M=1,5
          READ(1,90) TITLE(M)
          WRITE(2,90) TITLE(M)
        ENDDO
      IF(NWQOBS.GT.0)THEN
        DO M=1,NWQOBS
          READ(1,*) IWQCBS(M),JWQCBS(M),(WQOBCS(M,1,NW),NW=1,NWQV)
          WRITE(2,*) IWQCBS(M),JWQCBS(M),(WQOBCS(M,1,NW),NW=1,NWQV)
          WRITE(2,97) IWQCBS(M),JWQCBS(M),(WQOBCS(M,1,NW),NW=1,NWQV)
        ENDDO
      ENDIF
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      WRITE(2,999)
        DO M=1,5
          READ(1,90) TITLE(M)
          WRITE(2,90) TITLE(M)
        ENDDO
      IF(NWQOBS.GT.0)THEN
        DO M=1,NWQOBS
          READ(1,*) IWQCBS(M),JWQCBS(M),(WQOBCS(M,2,NW),NW=1,NWQV)
          WRITE(2,*) IWQCBS(M),JWQCBS(M),(WQOBCS(M,2,NW),NW=1,NWQV)
          WRITE(2,97) IWQCBS(M),JWQCBS(M),(WQOBCS(M,2,NW),NW=1,NWQV)
        ENDDO
      ENDIF
C
C WEST BDRY
C
C      DO M=1,2
C       READ(1,90) TITLE(M)
C       WRITE(2,90) TITLE(M)
C     ENDDO
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
        DO M=1,5
          READ(1,90) TITLE(M)
          WRITE(2,90) TITLE(M)
        ENDDO
      IF(NWQOBW.GT.0)THEN
        DO M=1,NWQOBW
          READ(1,*) IWQCBW(M),JWQCBW(M),(IWQOBW(M,NW),NW=1,NWQV)
          WRITE(2,*) IWQCBW(M),JWQCBW(M),(IWQOBW(M,NW),NW=1,NWQV)
          WRITE(2,969) IWQCBW(M),JWQCBW(M),(IWQOBW(M,NW),NW=1,NWQV)
        ENDDO
      ENDIF
C
C: CONSTANT BOTTOM AND SURFACE OBCS
C
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
        DO M=1,5
          READ(1,90) TITLE(M)
          WRITE(2,90) TITLE(M)
        ENDDO
      IF(NWQOBW.GT.0)THEN
        DO M=1,NWQOBW
          READ(1,*) IWQCBW(M),JWQCBW(M),(WQOBCW(M,1,NW),NW=1,NWQV)
          WRITE(2,*) IWQCBW(M),JWQCBW(M),(WQOBCW(M,1,NW),NW=1,NWQV)
          WRITE(2,97) IWQCBW(M),JWQCBW(M),(WQOBCW(M,1,NW),NW=1,NWQV)
        ENDDO
      ENDIF
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      WRITE(2,999)
        DO M=1,5
          READ(1,90) TITLE(M)
          WRITE(2,90) TITLE(M)
        ENDDO
      IF(NWQOBW.GT.0)THEN
        DO M=1,NWQOBW
          READ(1,*) IWQCBW(M),JWQCBW(M),(WQOBCW(M,2,NW),NW=1,NWQV)
          WRITE(2,*) IWQCBW(M),JWQCBW(M),(WQOBCW(M,2,NW),NW=1,NWQV)
          WRITE(2,97) IWQCBW(M),JWQCBW(M),(WQOBCW(M,2,NW),NW=1,NWQV)
        ENDDO
      ENDIF
C
C EAST BDRY
C
C      DO M=1,2
C       READ(1,90) TITLE(M)
C       WRITE(2,90) TITLE(M)
C     ENDDO
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
        DO M=1,5
          READ(1,90) TITLE(M)
          WRITE(2,90) TITLE(M)
        ENDDO
      IF(NWQOBE.GT.0)THEN
        DO M=1,NWQOBE
          READ(1,*) IWQCBE(M),JWQCBE(M),(IWQOBE(M,NW),NW=1,NWQV)
          WRITE(2,*) IWQCBE(M),JWQCBE(M),(IWQOBE(M,NW),NW=1,NWQV)
          WRITE(2,969) IWQCBE(M),JWQCBE(M),(IWQOBE(M,NW),NW=1,NWQV)
        ENDDO
       ENDIF
C
C: CONSTANT BOTTOM AND SURFACE OBCS
C
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
        DO M=1,5
          READ(1,90) TITLE(M)
          WRITE(2,90) TITLE(M)
        ENDDO
      IF(NWQOBE.GT.0)THEN
        DO M=1,NWQOBE
          READ(1,*) IWQCBE(M),JWQCBE(M),(WQOBCE(M,1,NW),NW=1,NWQV)
          WRITE(2,*) IWQCBE(M),JWQCBE(M),(WQOBCE(M,1,NW),NW=1,NWQV)
          WRITE(2,97) IWQCBE(M),JWQCBE(M),(WQOBCE(M,1,NW),NW=1,NWQV)
        ENDDO
      ENDIF
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
        DO M=1,5
          READ(1,90) TITLE(M)
          WRITE(2,90) TITLE(M)
        ENDDO
      IF(NWQOBE.GT.0)THEN
        DO M=1,NWQOBE
          READ(1,*) IWQCBE(M),JWQCBE(M),(WQOBCE(M,2,NW),NW=1,NWQV)
          WRITE(2,*) IWQCBE(M),JWQCBE(M),(WQOBCE(M,2,NW),NW=1,NWQV)
          WRITE(2,97) IWQCBE(M),JWQCBE(M),(WQOBCE(M,2,NW),NW=1,NWQV)
        ENDDO
      ENDIF
C
C NORTH BDRY
C
C      DO M=1,2
C       READ(1,90) TITLE(M)
C       WRITE(2,90) TITLE(M)
C     ENDDO
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,90) TITLE(1)
        DO M=1,5
          READ(1,90) TITLE(M)
          WRITE(2,90) TITLE(M)
        ENDDO
      IF(NWQOBN.GT.0)THEN
        DO M=1,NWQOBN
          READ(1,*) IWQCBN(M),JWQCBN(M),(IWQOBN(M,NW),NW=1,NWQV)
          WRITE(2,*) IWQCBN(M),JWQCBN(M),(IWQOBN(M,NW),NW=1,NWQV)
          WRITE(2,969) IWQCBN(M),JWQCBN(M),(IWQOBN(M,NW),NW=1,NWQV)
        ENDDO
      ENDIF
C
C: CONSTANT BOTTOM AND SURFACE OBCS
C
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
        DO M=1,5
          READ(1,90) TITLE(M)
          WRITE(2,90) TITLE(M)
        ENDDO
      IF(NWQOBN.GT.0)THEN
        DO M=1,NWQOBN
          READ(1,*) IWQCBN(M),JWQCBN(M),(WQOBCN(M,1,NW),NW=1,NWQV)
          WRITE(2,*) IWQCBN(M),JWQCBN(M),(WQOBCN(M,1,NW),NW=1,NWQV)
          WRITE(2,97) IWQCBN(M),JWQCBN(M),(WQOBCN(M,1,NW),NW=1,NWQV)
        ENDDO
      ENDIF
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
        DO M=1,5
          READ(1,90) TITLE(M)
          WRITE(2,90) TITLE(M)
        ENDDO
      IF(NWQOBN.GT.0)THEN
        DO M=1,NWQOBN
          READ(1,*) IWQCBN(M),JWQCBN(M),(WQOBCN(M,2,NW),NW=1,NWQV)
          WRITE(2,*) IWQCBN(M),JWQCBN(M),(WQOBCN(M,2,NW),NW=1,NWQV)
          WRITE(2,97) IWQCBN(M),JWQCBN(M),(WQOBCN(M,2,NW),NW=1,NWQV)
        ENDDO
      ENDIF
C
C SPATIALLY/TEMPORALLY CONSTANT INITIAL CONDITIONS: WQCHLX=1/WQCHLX
C READ DATA POINTS & DO INTERNAL INTERPOLATION?
C
C39
C   MODIFIED BY J.S.(5/5/98)
C
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0)THEN
        DO M=1,3
          READ(1,999)
        ENDDO
      ENDIF
      READ(1,*) (WQV(1,1,NW), NW=1,6)
      WRITE(2,*) (WQV(1,1,NW), NW=1,6)
      READ(1,*) (WQV(1,1,NW), NW=7,13)
      WRITE(2,*) (WQV(1,1,NW), NW=7,13)
      if(IDNOTRVA>0)then
        READ(1,*) (WQV(1,1,NW), NW=14,NWQV),WQV(1,1,IDNOTRVA),WQMCMIN
        WRITE(2,*) (WQV(1,1,NW), NW=14,NWQV),WQV(1,1,IDNOTRVA),WQMCMIN
      else
        READ(1,*) (WQV(1,1,NW), NW=14,NWQV),tmp,WQMCMIN
        WRITE(2,*) (WQV(1,1,NW), NW=14,NWQV),tmp,WQMCMIN
      endif
      IF(IWQICI.NE.1)THEN
        WRITE(2,999)
        WRITE(2,90) TITLE(1)
        WRITE(2,21)' : (BC, BD, BG)         = ', (WQV(1,1,NW),NW=1,3)
        WRITE(2,21)' : (RPOC, LPOC, DOC)    = ', (WQV(1,1,NW),NW=4,6)
        WRITE(2,21)' : (RPOP,LPOP,DOP,PO4T) = ', (WQV(1,1,NW),NW=7,10)
        WRITE(2,21)' : (RPON, LPON, DON)    = ', (WQV(1,1,NW),NW=11,13)
        WRITE(2,21)' : (NH4, NO3)           = ', (WQV(1,1,NW),NW=14,15)
        WRITE(2,21)' : (SU, SA, COD, DO)    = ', (WQV(1,1,NW),NW=16,19)
        WRITE(2,981)' : (TAM, FCB,MALG)     = ',
     *    (WQV(1,1,NW),NW=20,NWQV+1)
        WQCHL(1,1) = WQV(1,1,1)*WQCHLC + WQV(1,1,2)*WQCHLD
     *    + WQV(1,1,3)*WQCHLG
        IF(IWQSRP.EQ.1)THEN
          O2WQ = MAX(WQV(1,1,19), 0.0)
          WQTAMD = MIN( WQTAMDMX*EXP(-WQKDOTAM*O2WQ), WQV(1,1,20) )
          WQTAMP(1,1) = WQV(1,1,20) - WQTAMD
          WQPO4D(1,1) = WQV(1,1,10) / (1.0 + WQKPO4P*WQTAMP(1,1))
          WQSAD(1,1)  = WQV(1,1,17) / (1.0 + WQKSAP*WQTAMP(1,1))
         ELSE IF(IWQSRP.EQ.2)THEN
          WQPO4D(1,1) = WQV(1,1,10) / (1.0 + WQKPO4P*SEDT(1,1))
          WQSAD(1,1)  = WQV(1,1,17) / (1.0 + WQKSAP*SEDT(1,1))
         ELSE
          WQPO4D(1,1) = WQV(1,1,10)
          WQSAD(1,1)  = WQV(1,1,17)
        ENDIF
        DO NW=1,NWQV
         TVARWQ=WQV(1,1,NW)
         DO K=1,KC
          WQV(LC,K,NW) = TVARWQ
          WQV(1 ,K,NW) = TVARWQ
          WQVO(LC,K,NW) = TVARWQ
          WQVO(1 ,K,NW) = TVARWQ
         ENDDO
        ENDDO
        DO NW=1,NWQV
         TVARWQ=WQV(1,1,NW)
         DO ND=1,NDMWQ
          LF=2+(ND-1)*LDMWQ
          LL=LF+LDM-1
          DO K=1,KC
           DO L=LF,LL
            WQV(L,K,NW) = TVARWQ
           ENDDO
          ENDDO
         ENDDO
        ENDDO
        XWQCHL = WQCHL(1,1)
        XWQTAMP = WQTAMP(1,1)
        XWQPO4D = WQPO4D(1,1)
        XWQSAD = WQSAD(1,1)
        DO K=1,KC
         WQCHL(LC,K) = XWQCHL
         WQTAMP(LC,K) = XWQTAMP
         WQPO4D(LC,K) = XWQPO4D
         WQSAD(LC,K) = XWQSAD
         WQCHL(1,K) = XWQCHL
         WQTAMP(1,K) = XWQTAMP
         WQPO4D(1,K) = XWQPO4D
         WQSAD(1,K) = XWQSAD
        ENDDO
        DO ND=1,NDMWQ
         LF=2+(ND-1)*LDMWQ
         LL=LF+LDM-1
         DO K=1,KC
          DO L=LF,LL
           WQCHL(L,K) = XWQCHL
           WQTAMP(L,K) = XWQTAMP
           WQPO4D(L,K) = XWQPO4D
           WQSAD(L,K) = XWQSAD
          ENDDO
         ENDDO
        ENDDO
      ENDIF
C
C MODIFIED BY J.S.(5/5/98)
C
C READ CELL MAPPING FILE 'MACALGMP.INP' AND SET INITIAL CONDITION.
C MACROALGAE WILL RESIDE ONLY IN THE BOTTOM LAYER.
C
C 09/02/99 M.MORTON: ADDED KMV VELOCITY HALF-SATURATION, KBP DENSITY
C   HALF SATURATION, AND PSHADE FACTOR TO BETTER CONTROL MACROALGAE
C   GROWTH.
C
      IF(IDNOTRVA.GT.0)THEN
        DO L=1,LC
          SMAC(L)=0.0
          PSHADE(L)=1.0
          WQKMV(L)=0.25
          WQKMVMIN(L)=0.15
          WQKBP(L)=6.5
          WQKMVA(L)=1.0
          WQKMVB(L)=12.0
          WQKMVC(L)=0.3
          WQKMVD(L)=0.25
          WQKMVE(L)=2.0
        ENDDO
        WRITE(2,9003)
9003    FORMAT(/,' MACALGMP.INP - MACROALGAE MAP FILE',/,
     +   ' PSHADE = SHADE FACTOR FOR TREE CANOPY (1.0=NO CANOPY)',/,
     +   ' KMV    = MACROALGAE HALF-SATURATION VELOCITY (M/SEC)',/,
     +   ' KMVMIN = MACROALGAE VELOCITY LIMITATION MINIMUM (M/SEC)',/,
     +   ' KBP    = MACROALGAE HALF-SATURATION DENSITY (G C/M2)',/,
     +   ' KMVA   = MACROALGAE VEL. LIMIT LOGISTIC FUNC. PARAM. A',/,
     +   ' KMVB   = MACROALGAE VEL. LIMIT LOGISTIC FUNC. PARAM. B',/,
     +   ' KMVC   = MACROALGAE VEL. LIMIT LOGISTIC FUNC. PARAM. C',/,
     +   ' KMVD   = MACROALGAE VEL. LIMIT LOGISTIC FUNC. PARAM. D',/,
     +   ' KMVE   = MACROALGAE VEL. LIMIT LOGISTIC FUNC. PARAM. E',/,
     +   '   I   J   L PSHADE    KMV KMVMIN    KBP   KMVA   KMVB',
     +   '   KMVC   KMVD   KMVE')
        OPEN(3,FILE='MACALGMP.INP',STATUS='UNKNOWN')
        CALL SKIPCOMM(3, CCMRM)
9001    READ(3,*,END=9002) II, JJ, XMRM1, XMRM2, XMRM3, XMRM4,
     +   XMRMA, XMRMB, XMRMC, XMRMD, XMRME
        IF(II .LE. 0) GOTO 9002
        IF(IJCT(II,JJ).LT.1 .OR. IJCT(II,JJ).GT.8)THEN
          PRINT*, 'I, J, IJCT(I,J) = ', II,JJ,IJCT(II,JJ)
           STOP 'ERROR!! INVALID (I,J) IN FILE MACALGMP.INP'
        ENDIF
        LL=LIJ(II,JJ)
        SMAC(LL)=1.0
        PSHADE(LL)=XMRM1
        WQKMV(LL)=XMRM2
        WQKMVMIN(LL)=XMRM3
        WQKBP(LL)=XMRM4
        WQKMVA(LL)=XMRMA
        WQKMVB(LL)=XMRMB
        WQKMVC(LL)=XMRMC
        WQKMVD(LL)=XMRMD
        WQKMVE(LL)=XMRME
        WQV(LL,1,IDNOTRVA)=WQV(1,1,IDNOTRVA)
        WQVO(LL,1,IDNOTRVA)=WQV(1,1,IDNOTRVA)
        WRITE(2,9004) II, JJ, LL, PSHADE(LL), WQKMV(LL), WQKMVMIN(LL),
     +    WQKBP(LL), WQKMVA(LL), WQKMVB(LL), WQKMVC(LL), WQKMVD(LL),
     +    WQKMVE(LL)
9004    FORMAT(' ',I3,' ',I3,' ',I5, 9F7.3)
        GOTO 9001
9002    CLOSE(3)
        WQV(1,1,IDNOTRVA)=0.0
      ENDIF
C
C SPATIALLY/TEMPORALLY CONSTANT ALGAL GROWTH, RESPIRATION & PREDATION RATES
C
C
C40   MODIFIED BY J.S.(5/5/98)
C
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQPMC(1),WQPMD(1),WQPMG(1),WQPMM(1),WQBMRC(1),
     *    WQBMRD(1),WQBMRG(1),WQBMRM(1),WQPRRC(1),WQPRRD(1),
     *    WQPRRG(1),WQPRRM(1),WQKEB(1)
      WRITE(2,*) WQPMC(1),WQPMD(1),WQPMG(1),WQPMM(1),WQBMRC(1),
     *    WQBMRD(1),WQBMRG(1),WQBMRM(1),WQPRRC(1),WQPRRD(1),
     *    WQPRRG(1),WQPRRM(1),WQKEB(1)
      IF(IWQAGR.NE.1)THEN
        WRITE(2,999)
        WRITE(2,90) TITLE(1)
        WRITE(2,80)'* ALGAL GROWTH RATE (/DAY)                        '
        WRITE(2,21)' : (PMC, PMD, PMG)       = ', WQPMC(1),WQPMD(1),
     *    WQPMG(1)
        WRITE(2,80)'* ALGAL BASAL METABOLISM RATE (/DAY)              '
        WRITE(2,21)' : (BMRC, BMRD, BMRG)    = ', WQBMRC(1),WQBMRD(1),
     *    WQBMRG(1)
        WRITE(2,80)'* ALGAL PREDATION RATE (/DAY)                     '
        WRITE(2,21)' : (PRRC, PRRD, PRRG)    = ', WQPRRC(1),WQPRRD(1),
     *    WQPRRG(1)
        WRITE(2,82)
     *    '* BASE LIGHT EXTINCTION COEFFICIENT (/M)   = ',WQKEB(1)
C        WRITE(2,82)
C     *    '* WQSDCOEF (SECCHI DEPTH = WQSDCOEF/WQKESS)= ',WQSDCOEF(1)
        DO I=2,IWQZ
          WQPMC(I)=WQPMC(1)
          WQPMD(I)=WQPMD(1)
          WQPMG(I)=WQPMG(1)
          WQPMM(I)=WQPMM(1)
          WQBMRC(I)=WQBMRC(1)
          WQBMRD(I)=WQBMRD(1)
          WQBMRG(I)=WQBMRG(1)
          WQBMRM(I)=WQBMRM(1)
          WQPRRC(I)=WQPRRC(1)
          WQPRRD(I)=WQPRRD(1)
          WQPRRG(I)=WQPRRG(1)
          WQPRRM(I)=WQPRRM(1)
          WQKEB(I)=WQKEB(1)
C          WQSDCOEF(I)=WQSDCOEF(1)
        ENDDO
      ENDIF
C41
C SPATIALLY/TEMPORALLY CONSTANT SETTLING VELOCITIES AND REAERATION FACTOR
C
C     READ(1,999)
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*)WQWSC(1),WQWSD(1),WQWSG(1),WQWSRP(1),WQWSLP(1),WQWSS(1),
     *      WQWSM, REAC(1)
      WRITE(2,*)WQWSC(1),WQWSD(1),WQWSG(1),WQWSRP(1),WQWSLP(1),
     *      WQWSS(1),WQWSM, REAC(1)
      IF(IWQSTL.NE.1)THEN
        WRITE(2,999)
        WRITE(2,90) TITLE(1)
        WRITE(2,80)'* ALGAL SETTLING RATE (M/DAY)                     '
        WRITE(2,21)' : (WSC, WSD, WSG)       = ', WQWSC(1),WQWSD(1),
     *    WQWSG(1)
        WRITE(2,80)'* POM SETTLING RATE (M/DAY)                       '
        WRITE(2,21)' : (WSRP, WSLP)          = ', WQWSRP(1),WQWSLP(1)
        WRITE(2,80)'* SETTLING RATE OF PARTICULATE METAL (M/DAY)      '
        WRITE(2,21)' : (WSS)                 = ', WQWSS(1)
        DO I=2,IWQZ
          WQWSC(I)=WQWSC(1)
          WQWSD(I)=WQWSD(1)
          WQWSG(I)=WQWSG(1)
          WQWSRP(I)=WQWSRP(1)
          WQWSLP(I)=WQWSLP(1)
          WQWSS(I)=WQWSS(1)
          REAC(I)=REAC(1)
        ENDDO
      ENDIF
C
C SPATIALLY/TEMPORALLY CONSTANT BENTHIC FLUXES
C
C     READ(1,999)
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) WQBFPO4D(1),WQBFNH4(1),WQBFNO3(1),WQBFSAD(1),
     *  WQBFCOD(1),WQBFO2(1), STEMFAC
      WRITE(2,*) WQBFPO4D(1),WQBFNH4(1),WQBFNO3(1),WQBFSAD(1),
     *  WQBFCOD(1),WQBFO2(1)
      IF(IWQBEN.EQ.0)THEN
        WRITE(2,999)
        WRITE(2,90) TITLE(1)
        WRITE(2,21)' : (PO4D, NH4, NO3)     = ',WQBFPO4D(1),WQBFNH4(1),
     *    WQBFNO3(1)
        WRITE(2,21)' : (SAD, COD, DO)       = ',WQBFSAD(1),WQBFCOD(1),
     *    WQBFO2(1)
        DO L=2,LA
          WQBFPO4D(L)=WQBFPO4D(1)
          WQBFNH4(L)=WQBFNH4(1)
          WQBFNO3(L)=WQBFNO3(1)
          WQBFSAD(L)=WQBFSAD(1)
          WQBFCOD(L)=WQBFCOD(1)
          WQBFO2(L)=WQBFO2(1)
        ENDDO
      ENDIF
C
C TEMPORALLY-CONSTANT VALUES FOR POINT SOURCE INPUT IN (KG/D) EXCEPT
C XPSQ (M^3/S), XPO2 (G/M^3), XPTAM (KMOL/D), XPFCB (MPN/100ML).
C: IN GES, LOAD IS IN (G/D) EXCEPT TAM IN (MOL/D), FCB IN (MPN/100ML)*(M^3/S).
C: TO CONVERT KG/D TO G/D, (XW KG/D)*(10^3 G/KG) = (CONV1*XW G/D) WITH
C   CONV1=1.0E3.
C: FOR O2, (XPSQ M^3/S)*(XPO2 G/M^3)*(86400 S/D) = (CONV2*XPSQ*XPO2 G/D)
C   WITH CONV2=8.64E4.
C: FOR TAM, (XPTAM KMOL/D)*(10^3 MOL/KMOL) = (CONV1*XPTAM MOL/D).
C: FOR FCB, (XPFCB MPN/100ML)*(XPSQ M^3/S)*(86400 S/D) =
C   (CONV2*XPSQ*XPFCB (MPN/100ML)*M^3/D).
C
C     READ(1,999)
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
C11_24      IF(IWQPSL.NE.1)THEN
        WRITE(2,999)
        WRITE(2,90) TITLE(1)
C11_24      ENDIF
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      IF(ISSKIP .EQ. 0) READ(1,999)
      READ(1,*) IWQPS,NPSTMSR
      WRITE(2,*) IWQPS,NPSTMSR
      WRITE(2,23)'* NUMBER OF CELLS FOR POINT SOURCE INPUT  = ',IWQPS
      WRITE(2,23)'* NUMBER WITH VARIABLE POINT SOURCE INPUT = ',NPSTMSR
      IF(IWQPS.GT.NWQPS) STOP 'ERROR!! IWQPS SHOULD BE <= NWQPS'
C
C11_24      DO M=1,3
C11_24        READ(1,90) TITLE(M)
C11_24        IF(IWQPSL.NE.1) WRITE(2,90) TITLE(M)
C11_24      ENDDO
      DO M=1,3
        READ(1,90) TITLE(M)
        WRITE(2,90) TITLE(M)
      ENDDO
      DO M=1,IWQPS
        READ(1,*) I,J,K,ITMP,XPSQ,(XPSL(NW),NW=1,6)
        WRITE(2,*) I,J,K,ITMP,XPSQ,(XPSL(NW),NW=1,6)
        READ(1,*) (XPSL(NW),NW=7,13)
        WRITE(2,*) (XPSL(NW),NW=7,13)
        READ(1,*) (XPSL(NW),NW=14,NWQV)
        WRITE(2,*) (XPSL(NW),NW=14,NWQV)
C11_24        IF(IWQPSL.NE.1)THEN
          WRITE(2,294) I,J,K,ITMP,XPSQ,(XPSL(NW),NW=1,NWQV)
          IF(IJCT(I,J).LT.1 .OR. IJCT(I,J).GT.8)THEN
            WRITE(*,911) I,J
  911       FORMAT(/,' I,J = ', 2I5)
            STOP 'ERROR!! INVALID (I,J) IN FILE WQ3DWC.INP FOR PSL'
          ENDIF
C
CMRM M.R. MORTON  02/20/1999
CMRM ADDED A FIX HERE SO THAT MULTIPLE POINT SOURCE LOADS (PSL) CAN BE ADDED
CMRM TO THE SAME I,J CELL.  IN ORIGINAL CODE, THE PSL READ IN LAST
CMRM OVERWRITES ANY EARLIER PSLS IN THE SAME I,J CELL.
CMRM    M = POINT SOURCE NUMBER
CMRM    K = LAYER IN WHICH POINT SOURCE IS INTRODUCED
CMRM    L = CELL NUMBER FOR LOCATION I,J
CMRM    IWQPSC(L,K) = M, INDEX POINTER TO CONSTANT PSL NUMBER
CMRM    IWQPSV(L,K) = INDEX POINTER TO TIME-VARIABLE PSL IN WQPSL.INP
CMRM    ICPSL(M) = SAVES I CELL INDEX OF PSL M
CMRM    JCPSL(M) = SAVES J CELL INDEX OF PSL M
CMRM    KCPSL(M) = SAVES K LAYER INDEX OF PSL M
CMRM    MVPSL(M) = INDEX POINTER TO TIME-VARIABLE PSL IN WQPSL.INP
          L = LIJ(I,J)
C JMH MODIFIED 5/18/00 TO ALLOW KCPSL(M) TO BE SET TO ZERO FOR UNIFORM DISTRIBUTION
C OF LOAD IN HORIZONTAL CELL STACK OVER ALL LAYERS
          DO KK=1,KC
            IWQPSC(L,KK)=M
            IWQPSV(L,KK)=ITMP
          ENDDO
          ICPSL(M)=I
          JCPSL(M)=J
          KCPSL(M)=K
          MVPSL(M)=ITMP
          WQPSQC(M)=XPSQ
          DO NW=1,18
            WQWPSLC(M,NW) = XPSL(NW) * CONV1
          ENDDO
          WQTT = XPSQ*CONV2
          WQWPSLC(M,19) = XPSL(19) * WQTT
          WQWPSLC(M,20) = XPSL(20) * CONV1
          WQWPSLC(M,NWQV) = XPSL(NWQV) * WQTT
C11_24        ENDIF
      ENDDO
C
C SPATIALLY/TEMPORALLY-CONSTANT VALUES FOR NON-POINT SOURCE INPUT IN (KG/D)
C EXCEPT XDSQ (M^3/S), XNO2 (MG/L), XNTAM (KMOL/D), XNFCB (MPN/100ML).
C MRM  NOTE: THIS GROUP IS NOW USED FOR DRY ATMOSPHERIC DEPOSITION WITH
C      CONSTITUENT UNITS OF G/M2/DAY EXCEPT FCB WHICH IS MPN/M2/DAY.
C
C     READ(1,999)
      WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      DO M=1,3
        READ(1,999)
      ENDDO
      READ(1,*) XDSQ,(XDSL(NW),NW=1,6)
      WRITE(2,*) XDSQ,(XDSL(NW),NW=1,6)
      READ(1,*) (XDSL(NW),NW=7,13)
      WRITE(2,*) (XDSL(NW),NW=7,13)
      READ(1,*) (XDSL(NW),NW=14,NWQV)
      WRITE(2,*) (XDSL(NW),NW=14,NWQV)
      IF(IWQNPL.NE.1)THEN
        WRITE(2,999)
        WRITE(2,90) TITLE(1)
        WRITE(2,21)' : (DSQ, BC, BD, BG)     = ',XDSQ,(XDSL(NW),NW=1,3)
        WRITE(2,21)' : (RPOC, LPOC, DOC)     = ',(XDSL(NW),NW=4,6)
        WRITE(2,21)' : (RPOP,LPOP,DOP,PO4T)  = ',(XDSL(NW),NW=7,10)
        WRITE(2,21)' : (RPON, LPON, DON)     = ',(XDSL(NW),NW=11,13)
        WRITE(2,21)' : (NH4, NO3)            = ',(XDSL(NW),NW=14,15)
        WRITE(2,21)' : (SU, SA, COD, DO)     = ',(XDSL(NW),NW=16,19)
        WRITE(2,981)' : (TAM, FCB)            = ',(XDSL(NW),NW=20,NWQV)
        WQDSQ(1,1) = XDSQ
        DO NW=1,18
          WQWDSL(1,1,NW) = XDSL(NW) * CONV1
        ENDDO
        WQTT = XDSQ*CONV2
        WQWDSL(1,1,19) = XDSL(19) * WQTT
        WQWDSL(1,1,20) = XDSL(20) * CONV1
        WQWDSL(1,1,NWQV) = XDSL(NWQV) * WQTT
C
        DO L=2,LA
          WQDSQ(L,1)=WQDSQ(1,1)
          DO NW=1,NWQV
C M. MORTON MODIFIED THE LINE BELOW SO THAT CONSTANT ATMOSPHERIC DEPOSITION
C CAN BE ADDED VIA THIS ROUTINE INSTEAD OF CONSTANT NPS INPUT WHICH THE
C ORIGINAL CODE CALLED FOR AND WHICH WAS NOT PARTICULARLY USEFUL.
C INPUT DATA (XDSL) ARE IN G/M2/DAY AND ARE MULTIPLIED BY THE CELL SURFACE
C AREA (DXYP) TO GET G/DAY.  ATMOSPHERIC DEPOSITION ONLY ENTERS THRU SURFACE
C LAYER (KC):
C            WQWDSL(L,1,NW)=WQWDSL(1,1,NW)
            WQWDSL(L,KC,NW) = XDSL(NW) * DXYP(L)
          ENDDO
        ENDDO
      ENDIF
C
C MRM THIS IS A NEW CARD GROUP ADDED 06/08/98 FOR WET ATMOSPHERIC
C     DEPOSITION.  THE VALUES FOR EACH WQ CONSTITUENT ARE IN MG/L AND
C     WILL BE MULTIPLIED BY THE RAINFALL FLOW RATE INTO EACH GRID CELL
C     TO GET A LOAD IN KG/DAY.
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,999)
      DO M=1,3
        READ(1,999)
      ENDDO
      READ(1,*) (WQATM(NW),NW=1,6)
      WRITE(2,*) (WQATM(NW),NW=1,6)
      READ(1,*) (WQATM(NW),NW=7,13)
      WRITE(2,*) (WQATM(NW),NW=7,13)
      READ(1,*) (WQATM(NW),NW=14,NWQV)
      WRITE(2,*) (WQATM(NW),NW=14,NWQV)
      WRITE(2,999)
      WRITE(2,90) TITLE(1)
      WRITE(2, 21)' : (BC, BD, BG)          = ',(WQATM(NW),NW=1,3)
      WRITE(2, 21)' : (RPOC, LPOC, DOC)     = ',(WQATM(NW),NW=4,6)
      WRITE(2, 21)' : (RPOP,LPOP,DOP,PO4T)  = ',(WQATM(NW),NW=7,10)
      WRITE(2, 21)' : (RPON, LPON, DON)     = ',(WQATM(NW),NW=11,13)
      WRITE(2, 21)' : (NH4, NO3)            = ',(WQATM(NW),NW=14,15)
      WRITE(2, 21)' : (SU, SA, COD, DO)     = ',(WQATM(NW),NW=16,19)
      WRITE(2,981)' : (TAM, FCB)            = ',(WQATM(NW),NW=20,NWQV)

C
C INPUT/OUTPUT FILE NAMES FOR SPATIALLY AND/OR TEMPORALLY VARYING PARAMETERS
C
C     READ(1,999)
C     WRITE(2,999)
      IF(ISSKIP .GT. 0) CALL SKIPCOMM(1,CCMRM)
      READ(1,90) TITLE(1)
      WRITE(2,999)
      WRITE(2,90) TITLE(1)
C
      READ(1,295) RSTOFN
      WRITE(2,85)'* OUTPUT FILE FOR RESTART WRITING         = ', RSTOFN
      IF(IWQRST.EQ.1)THEN
        OPEN(99,FILE=RSTOFN,STATUS='UNKNOWN')
        CLOSE(99,STATUS='DELETE')
        OPEN(99,FILE=RSTOFN,STATUS='UNKNOWN')
CXH        OPEN(UNIT=IWQORST,FILE=RSTOFN,STATUS='UNKNOWN')
        WRITE(99,888)
        CLOSE(99)
       ELSE
        IF(RSTOFN(1:4).NE.'NONE')
     &          STOP 'ERROR!! INVALID IWQORST/RSTOFN'
      ENDIF
  888 FORMAT('    L    K',
     *'          BC          BD          BG        RPOC        LPOC',
     *'         DOC        RPOP        LPOP         DOP        PO4T',
     *'        RPON        LPON         DON         NH4         NO3',
     *'          SU          SA         COD          O2         TAM',
     *'         FCB')
C
      READ(1,295) ICIFN
      WRITE(2,85)'* FILE FOR INITIAL CONDITIONS             = ', ICIFN
      IF(IWQICI.EQ.1)THEN
CXH        OPEN(UNIT=INWQICI,FILE=ICIFN,STATUS='OLD')
       ELSE IF(IWQICI.EQ.2)THEN
CXH        OPEN(UNIT=INWQRST,FILE=ICIFN,STATUS='OLD')
       ELSE
        IF(ICIFN(1:4).NE.'NONE') STOP 'ERROR!! INVALID IWQICI/ICIFN'
      ENDIF
C
C      READ(1,295) OBCFN
C      WRITE(2,85)'* FILE FOR DOWNRIVER BOUNDARY CONDITIONS  = ', OBCFN
C      IF(IWQOBC.EQ.1)THEN
C        OPEN(UNIT=INWQOBC,FILE=OBCFN,STATUS='OLD')
C       ELSE
C        IF(OBCFN(1:4).NE.'NONE') STOP 'ERROR!! INVALID IWQOBC/OBCFN'
C      ENDIF
C
      READ(1,295) AGRFN
      WRITE(2,85)'* FILE FOR ALGAL GROWTH, RESP., PREDATAT. = ', AGRFN
      IF(IWQAGR.EQ.1)THEN
CXH        OPEN(UNIT=INWQAGR,FILE=AGRFN,STATUS='OLD')
       ELSE
        IF(AGRFN(1:4).NE.'NONE') STOP 'ERROR!! INVALID IWQAGR/AGRFN'
      ENDIF
C
      READ(1,295) STLFN
      WRITE(2,85)'* FILE FOR SETTLING RATES OF ALGAE, PART. = ', STLFN
      IF(IWQSTL.EQ.1)THEN
CXH        OPEN(UNIT=INWQSTL,FILE=STLFN,STATUS='OLD')
       ELSE
        IF(STLFN(1:4).NE.'NONE') STOP 'ERROR!! INVALID IWQSTL/STLFN'
      ENDIF
C
      READ(1,295) SUNFN
      WRITE(2,85)'* FILE FOR IO, FD, TE, KT                 = ', SUNFN
      IF(IWQSUN.EQ.1)THEN
CXH        OPEN(UNIT=INWQSUN,FILE=SUNFN,STATUS='OLD')
       ELSE
        IF(SUNFN(1:4).NE.'NONE') STOP 'ERROR!! INVALID IWQSUN/SUNFN'
      ENDIF
C
      READ(1,295) BENFN
      WRITE(2,85)'* FILE FOR BENTHIC FLUX                   = ', BENFN
      IF(IWQBEN.EQ.2)THEN
CXH        OPEN(UNIT=INWQBEN,FILE=BENFN,STATUS='OLD')
       ELSE
        IF(BENFN(1:4).NE.'NONE') STOP 'ERROR!! INVALID IWQBEN/BENFN'
      ENDIF
C
      READ(1,295) PSLFN
      WRITE(2,85)'* FILE FOR POINT SOURCE INPUT             = ', PSLFN
C11_24      IF(IWQPSL.EQ.1)THEN
CXH        OPEN(UNIT=INWQPSL,FILE=PSLFN,STATUS='OLD')
C11_24       ELSE
C11_24        IF(PSLFN(1:4).NE.'NONE') STOP 'ERROR!! INVALID IWQPSL/PSLFN'
C11_24      ENDIF
C
      READ(1,295) NPLFN
      WRITE(2,85)'* FILE FOR NPS INPUT INCLUDING ATM. INPUT = ', NPLFN
      IF(IWQNPL.EQ.1)THEN
CXH        OPEN(UNIT=INWQNPL,FILE=NPLFN,STATUS='OLD')
       ELSE
        IF(NPLFN(1:4).NE.'NONE') STOP 'ERROR!! INVALID IWQNPL/NPLFN'
      ENDIF
C
      READ(1,295) NCOFN
      WRITE(2,85)'* DIAGNOSTIC FILE FOR NEGATIVE CONCENTRAT = ', NCOFN
C
      CLOSE(1)
C      WRITE(6,6666)'READ WQ3DWC.INP'
C
      IF(IWQNC.EQ.1)THEN
        OPEN(1,FILE=NCOFN,STATUS='UNKNOWN')
        CLOSE(1,STATUS='DELETE')
        OPEN(1,FILE=NCOFN,STATUS='UNKNOWN')
CXH        OPEN(UNIT=IWQONC,FILE=NCOFN)
        WRITE(1,284)'* NEGATIVE CONCENTRATION OCCURS:'
        CLOSE(1)
       ELSE
        IF(NCOFN(1:4).NE.'NONE') STOP 'ERROR!! INVALID IWQNC/NCOFN'
      ENDIF
C
  294 FORMAT(2I4,2I3, 7F8.3, /, 14X, 7F8.3, /, 14X, 8F8.3)
  295 FORMAT(44X, A50)
   96 FORMAT(2I5, 13I5, /, 10X, 8I5)
  969 FORMAT(2I4,1X,21I3)
  970 FORMAT(1X,21I3)
   97 FORMAT(2I4, 6F8.3, /, 8X, 7F8.3, /, 8X, 8F8.3)
   98 FORMAT(6F8.4, /, 7F8.4, /, 8F8.4)
   99 FORMAT(7F8.4, /, 7F8.4, /, 8F8.4)
C MRM  21 FORMAT(A27, 4(F8.3,2X))
   21 FORMAT(A27, 1P, 4E11.3)
C MRM  981 FORMAT(A27, F8.3,2X,F8.2,2X,F8.2)
  981 FORMAT(A27, 1P, 3E11.3)
   23 FORMAT(A46, I5)
   85 FORMAT(A44, A50)
  284 FORMAT(A32, /, 'NAME    ITNWQ    L    I    J    K       CONC')
C
C MRM READ FILE KINETICS.INP FOR SPATIALLY-VARYING KINETICS PARAMETERS:
C
      DO I=1,IWQZ
        IWQKA(I)=IWQKA(1)
        WQKRO(I)=WQKRO(1)
C ERROR       WQKTR(I)=WQKRO(1)
        WQKTR(I)=WQKTR(1)
        REAC(I)=REAC(1)
        WQKDC(I)=WQKDC(1)
        WQKDCALM(I)=WQKDCALM(1)
        WQKHRM(I)=WQKHRM(1)
        WQDOPM(I)=WQDOPM(1)
        WQKCD(I)=WQKCD(1)
        WQKHCOD(I)=WQKHCOD(1)
      ENDDO
      IF(IWQZ .GT. 1 .AND. IWQKIN .GT. 0)THEN
        OPEN(1,FILE='KINETICS.INP',STATUS='UNKNOWN')
        CALL SKIPCOMM(1,CCMRM)
        WRITE(2,*) ' '
        WRITE(2,*) ' SPATIALLY-VARYING KINETICS.INP FILE'
        WRITE(2,9111)
        DO I=1,IWQZ
          READ(1,*) IZ, IWQKA(IZ), WQKRO(IZ), WQKTR(IZ), REAC(IZ),
     +     WQKDC(IZ), WQKDCALM(IZ), WQKHRM(IZ), WQDOPM(IZ), WQKCD(IZ),
     +     WQKHCOD(IZ)
          WRITE(2,*) IZ, IWQKA(IZ), WQKRO(IZ), WQKTR(IZ), REAC(IZ),
     +     WQKDC(IZ), WQKDCALM(IZ), WQKHRM(IZ), WQDOPM(IZ), WQKCD(IZ),
     +     WQKHCOD(IZ)
          WRITE(2,9112) IZ, IWQKA(IZ), WQKRO(IZ), WQKTR(IZ), REAC(IZ),
     +     WQKDC(IZ), WQKDCALM(IZ), WQKHRM(IZ), WQDOPM(IZ), WQKCD(IZ),
     +     WQKHCOD(IZ)
        ENDDO
        CLOSE(1)
      ENDIF
9111  FORMAT(/,'ZONE IWQKA   KRO   KTR  REAC   KDC KDCALGM  KHRM',
     + ' DOPTM   KCD KHCOD')
9112  FORMAT(I4, I6, 4F6.3, F8.3, 4F6.3)
C
C SET UP LOOK-UP TABLE FOR TEMPERATURE DEPENDENCY OVER -15OC TO 40OC
C
      DO M=1,NWQTD
C        WTEMP =1.00*REAL(M-1)*0.5 - 4.95
        WTEMP =1.00*REAL(M-1)*0.1 - 14.95
        TT20 = WTEMP-20.0
        DO I=1,IWQZ
          WQKCOD(M,I) = WQKCD(I) * EXP( WQKTCOD*(WTEMP-WQTRCOD) )
          WQTDKR(M,I) = WQKTR(I)**TT20
            WRITE(2,2223)M,I,WQKTR(I),WQTDKR(M,I)
        ENDDO
      ENDDO
  
C
C READ IN MAPPING INFORMATION FOR SPATIALLY-VARYING PARAMETERS (UNIT #7).
C
      DO K=1,KC
       DO L=2,LA
        IWQZMAP(L,K)=1
       ENDDO
      ENDDO
C
C MRM REMOVED THE FOLLOWING HARDWIRE SO WQWCMAP.INP WILL BE READ WHENEVER
C     IWQZ IS GREATER THAN 1 WHICH IMPLIES THE MAP FILE MUST BE READ IN:
C      IF(ISWQCMAP.EQ.1)THEN
      IF(IWQZ .GT. 1)THEN
C
       OPEN(1,FILE='WQWCMAP.INP',STATUS='UNKNOWN')
C
       WRITE(2,999)
       READ(1,30) (TITLE(M), M=1,3)
       WRITE(2,30) (TITLE(M), M=1,3)
C      READ(1,999)
       READ(1,999)
       WRITE(2,999)
       WRITE(2,32)
       IN=0
       IJKC=IC*JC*KC
       DO M=1,IJKC
        READ(1,*,END=1111) I,J,K,IWQZX
        IN=IN+1
        IF(IJCT(I,J).LT.1 .OR. IJCT(I,J).GT.8)THEN
          PRINT*, 'I, J, K, IJCT(I,J) = ', I,J,K,IJCT(I,J)
          STOP 'ERROR!! INVALID (I,J) IN FILE WQWCMAP.INP'
        ENDIF
        L = LIJ(I,J)
        IWQZMAP(L,K)=IWQZX
        WRITE(2,31) L,I,J,K,IWQZMAP(L,K)
       ENDDO
 1111  CONTINUE
       IF(IN.NE.(LA-1)*KC)THEN
        PRINT*, 'ALL ACTIVE WATER CELLS SHOULD BE MAPPED FOR WQ PAR.'
        STOP 'ERROR!! NUMBER OF LINES IN FILE WQWCMAP.INP =\ (LA-1)'
       ENDIF
C
       CLOSE(1)
C
      ENDIF
C      WRITE(6,6666)'READ WQWCMAP.INP'
C
C MRM CODE BELOW ADDED BY M. MORTON 03/29/98:
C READ IN MAPPING INFORMATION FOR SPATIALLY-VARYING BENTHIC FLUXES.
C FORMULATED FOR PECONIC BAY DATA WHICH INCLUDES %MUD FOR EACH CELL AS
C WELL AS MAPPING TO BOTH MUD AND SAND FLUXES.  SUBROUTINE RWQBEN2
C CONTAINS THE CODE TO INTERPOLATE THE FINAL FLUX FOR THE CELL BASED
C ON THE PERCENT MUD AND THE MUD/SAND FLUXES.
C
      IF(IWQBEN .EQ. 2)THEN
C
       DO K=1,2
        DO L=2,LA
         IBENMAP(L,K)=1
         XBENMUD(L) = 0.50
        ENDDO
       ENDDO
C
       OPEN(1,FILE='WQBENMAP.INP',STATUS='UNKNOWN')
C
       WRITE(2,999)
       DO M=1,4
        READ(1,30) TITLE(M)
        WRITE(2,30) TITLE(M)
       ENDDO
C
C SKIP ALL COMMENT CARDS AT BEGINNING OF FILE:
C
       REWIND(1)
       CCMRM = '#'
       CALL SKIPCOMM(1, CCMRM)
C       READ(1,999)
       WRITE(2,999)
       WRITE(2,33)
       IN=0
       IJKC=IC*JC
       DO M=1,IJKC
         READ(1,*,END=1112) I, J, XMUD, IZMUD, IZSAND
         IN=IN+1
         IF(IJCT(I,J).LT.1 .OR. IJCT(I,J).GT.8)THEN
           PRINT*, 'I, J, K, IJCT(I,J) = ', I,J,IJCT(I,J)
           STOP 'ERROR!! INVALID (I,J) IN FILE WQBENMAP.INP'
         ENDIF
         L = LIJ(I,J)
         IBENMAP(L,1) = IZMUD
         IBENMAP(L,2) = IZSAND
         XBENMUD(L) = XMUD / 100.0
         WRITE(2,34) L, I, J, XBENMUD(L), IBENMAP(L,1), IBENMAP(L,2)
       ENDDO
 1112  CONTINUE
       IF(IN .NE. (LA-1))THEN
         PRINT*, 'ALL ACTIVE WATER CELLS SHOULD BE MAPPED FOR WQ PAR.'
         STOP 'ERROR!! NUMBER OF LINES IN FILE WQBENMAP.INP <> (LA-1)'
       ENDIF
C
       CLOSE(1)
C
      ENDIF
C      WRITE(6,6666)'READ WQBENMAP.INP'
C
CMRM CODE ABOVE TO PREVIOUS CMRM ADDED BY M. MORTON 03/29/98.
      CLOSE(2)
C
 2222 FORMAT(' M,WQKTR(1),WQTDKR(M,1) = ',I5,2F10.4)
 2223 FORMAT(' M,I,WQKTR(1),WQTDKR(M,I) = ',2I5,2F10.4)
   30 FORMAT(A79)
   31 FORMAT(15I5)
   32 FORMAT('    L    I    J    L IWQZMAP')
   33 FORMAT('     L    I    J   MUD IZMUD IZSAND')
   34 FORMAT(' ',3I5, F6.2, 2I6)
C
      RETURN
      END
