C
C**********************************************************************C
C**********************************************************************C
C**********************************************************************C
C
      SUBROUTINE TOXALL
C
C **  SUBROUTINE TOXALL WRITES ACCUMULATED TOXIC FLUXES
C
C **  THIS SUBROUTINE IS PART OF  EFDC-FULL VERSION 1.0a 
C
C **  LAST MODIFIED BY JOHN HAMRICK ON 1 NOVEMBER 2001
C
C**********************************************************************C
C
C     VARIABLES WRITTEN TO TOXALL.OUT
C
C       ATOXPFWX  (L,NS,NT)= PARTICULATE ADVECTIVE X FLUX IN WATER COLUMN  NS=1,NSED+NSND+2
C       ATOXPFWY  (L,NS,NT)= PARTICULATE ADVECTIVE Y FLUX IN WATER COLUMN  NS=1,NSED+NSND+2
C       ATOXFDFWX (L,NT)   = FREE DISSOLVED ADVECTIVE X FLUX IN WATER COLUMN
C       ATOXFDFWY (L,NT)   = FREE DISSOLVED ADVECTIVE Y FLUX IN WATER COLUMN
C       ATOXCDFWX (L,NT)   = COMPLEXED DISSOLVED ADVECTIVE X FLUX IN WATER COLUMN
C       ATOXCDFWY (L,NT)   = COMPLEXED DISSOLVED ADVECTIVE Y FLUX IN WATER COLUMN
C       ATOXPFBLX (L,NS,NT)= BEDLOAD FLUX IN X DIRECTION, NS=1,NSND
C       ATOXPFBLY (L,NS,NT)= BEDLOAD FLUX IN Y DIRECTION, NS=1,NSND
C       ATOXSOUR  (L,NT)   = INFLOW FLUX TO WATER COLUMN
C       ATOXSINK  (L,NT)   = OUTFLOW FLUX FROM WATER COLUMN (WILL ALWAYS BE NEGATIVE)
C       ATOXVOL   (L,NT)   = VOLIIZATION FLUX FROM WATER COLUMN (WILL ALWAYS BE NEGATIVE)
C       ATOXPFBW  (L,NS,NT)= NET PARTICULATE FLUX FROM BED TO WATER COLUMN, NS=1,NSED+NSND+2
C       ATOXFDFBW (L,NT)   = NET FREE DISSOLVED FLUX FROM BED TO WATER COLUMN
C       ATOXCDFBW (L,NT)   = NET COMPLEXED DISSOLVED FLUX FROM BED TO WATER COLUMN
C       ATOXFBEBKB(L,NT)   = FLUX FORM BANK CELL DUE TO BANK EROSION
C       ATOXFBECHB(L,NT)   = FLUX TO CHANNEL BED DUE TO BANK EROSION
C       ATOXFBECHW(L,NT)   = FLUX TO CHANNEL WATER COLUMN DUE TO BANK EROSION
C
C     VARIABLES WRITTEN TO TOXALLB2W.OUT   (FLUXES BED TO WATER)
C
C       ATOXPFBWP (L,NS,NT)= POSITIVE ARTICULATE FLUX FROM BED TO WATER COLUMN, NS=1,NSED+NSND+2
C       ATOXFDFBWP(L,NT)   = POSITIVE FREE DISSOLVED FLUX FROM BED TO WATER COLUMN
C       ATOXCDFBWP(L,NT)   = POSITIVE COMPLEXED DISSOLVED FLUX FROM BED TO WATER COLUMN
C
C     VARIABLES WRITTEN TO OXALLW2B.OUT   (FLUXES WATER TO BED)
C
C       ATOXPFBWN (L,NS,NT)= NEGATIVE PARTICULATE FLUX FROM BED TO WATER COLUMN (IE WATER TO BED), NS=1,NSED+NSND+2
C       ATOXFDFBWN(L,NT)   = NEGATIVE FREE DISSOLVED FLUX FROM BED TO WATER COLUMN (IE WATER TO BED)
C       ATOXCDFBWN(L,NT)   = NEGATIVE COMPLEXED DISSOLVED FLUX FROM BED TO WATER COLUMN (IE WATER TO BED)
C
C     VARIBALES WRITTEN TO TOXALLBWAD.OUT  (PORE WATER ADVECTION AND DIFFUSION)
C
C       ATOXFDFBWAD(L,NT) = NET FREE DISSOLVED POREWATER FLUX FROM BED TO WATER COLUMN
C       ATOXCDFBWAD(L,NT) = NET COMPLEXED DISSOLVED POREWATER FLUX FROM BED TO WATER COLUMN
C
C     VARIBALES WRITTEN TO TOXALLB2WAD.OUT (PORE WATER ADVECTION AND DIFFUSION (FLUXES BED TO WATER)
C
C       ATOXFDFBWADP(L,NT)= POSITIVE FREE DISSOLVED POREWATER FLUX FROM BED TO WATER COLUMN
C       ATOXCDFBWADN(L,NT)= POSITIVE COMPLEXED DISSOLVED POREWATER FLUX FROM BED TO WATER COLUMN
C
C     VARIBALES WRITTEN TO TOXALLW2BAD.OUT (PORE WATER ADVECTION AND DIFFUSION (FLUXES WATER TO BED)
C
C       ATOXFDFBWADP(L,NT)= NEGATIVE FREE DISSOLVED POREWATER FLUX FROM BED TO WATER COLUMN (IE WATER TO BED)
C       ATOXCDFBWADP(L,NT)= NEGATIVE COMPLEXED DISSOLVED POREWATER FLUX FROM BED TO WATER COLUMN (IE WATER TO BED)
C
C**********************************************************************C
C
      INCLUDE 'EFDC.PAR'
      INCLUDE 'EFDC.CMN'
C
      CHARACTER*18 FNTMP(7)
C
C**********************************************************************C
C
       FNTMP(1)='TOXALL_PFWCADV.OUT'
       FNTMP(2)='TOXALL_FDWCADV.OUT'
       FNTMP(3)='TOXALL_PFBEDLD.OUT'
       FNTMP(4)='TOXALL_SORSINK.OUT'
       FNTMP(5)='TOXALL_PFBD2WC.OUT'
       FNTMP(6)='TOXALL_FDBD2WC.OUT'
       FNTMP(7)='TOXALL_BANKERO.OUT'
C
C**********************************************************************C
C
      IF(JSTOXALL.EQ.0)THEN
        OPEN(1,FILE='TOXALL.OUT')
        OPEN(2,FILE='TOXALLBW.OUT')
        OPEN(3,FILE='TOXALLB2W.OUT')
        OPEN(4,FILE='TOXALLW2B.OUT')
        OPEN(11,FILE='TOXALLBWAD.OUT')
        OPEN(12,FILE='TOXALLB2WAD.OUT')
        OPEN(13,FILE='TOXALLW2BAD.OUT')
        OPEN(14,FILE='SEDALL.OUT')
        CLOSE(1,STATUS='DELETE')
        CLOSE(2,STATUS='DELETE')
        CLOSE(3,STATUS='DELETE')
        CLOSE(4,STATUS='DELETE')
        CLOSE(11,STATUS='DELETE')
        CLOSE(12,STATUS='DELETE')
        CLOSE(13,STATUS='DELETE')
        CLOSE(14,STATUS='DELETE')
C
C   DEBUGGING FILES
C
C         DO IUNIT=21,27
C           IUNITF=IUNIT-20
C           OPEN(IUNIT,FILE=FNTMP(IUNITF))
C           CLOSE(IUNIT,STATUS='DELETE')
C         ENDDO
C
        JSTOXALL=1
      ENDIF
C
C**********************************************************************C
C
      OPEN(1,FILE='TOXALL.OUT',POSITION='APPEND')
      OPEN(2,FILE='TOXALLBW.OUT',POSITION='APPEND')
      OPEN(3,FILE='TOXALLB2W.OUT',POSITION='APPEND')
      OPEN(4,FILE='TOXALLW2B.OUT',POSITION='APPEND')
      OPEN(11,FILE='TOXALLBWAD.OUT',POSITION='APPEND')
      OPEN(12,FILE='TOXALLB2WAD.OUT',POSITION='APPEND')
      OPEN(13,FILE='TOXALLW2BAD.OUT',POSITION='APPEND')
      OPEN(14,FILE='SEDALL.OUT',POSITION='APPEND')
C
C  DEBUGGING FILES
C
C       DO IUNIT=21,27
C         IUNITF=IUNIT-20
C         OPEN(IUNIT,FILE=FNTMP(IUNITF),POSITION='APPEND')
C       ENDDO
C
      IF(ISDYNSTP.EQ.0)THEN
        TIME=(DT*FLOAT(N)+TCON*TBEGIN)/86400.
      ELSE
        TIME=TIMESEC/86400.
      ENDIF
C
      WRITE(1,100)TIME
      WRITE(2,100)TIME
      WRITE(3,100)TIME
      WRITE(4,100)TIME
      WRITE(11,100)TIME
      WRITE(12,100)TIME
      WRITE(13,100)TIME
      WRITE(14,100)TIME
C
C      DO IUNIT=21,27
C        WRITE(IUNIT,100)TIME
C      ENDDO
C
C      NTMP=NSED+NSND+2
      NTMP=NSED+NSND
C
      NT=1
      DO L=2,LA
        WRITE(1,101)IL(L),JL(L),      
     &  (ATOXPFWX(L,NS,NT),NS=1,NTMP),(ATOXPFWY(L,NS,NT),NS=1,NTMP),
     &   ATOXFDFWX(L,NT),ATOXFDFWY(L,NT),ATOXCDFWX(L,NT),
     &   ATOXCDFWY(L,NT),
     &  (ATOXPFBLX(L,NS,NT),NS=1,NSND),(ATOXPFBLY(L,NS,NT),NS=1,NSND),
     &   ATOXSOUR(L,NT),ATOXSINK(L,NT),ATOXVOL(L,NT),
     &  (ATOXPFBW(L,NS,NT),NS=1,NTMP),ATOXFDFBW(L,NT),
     &  ATOXCDFBW(L,NT),ATOXFBEBKB(L,NT),
     &   ATOXFBECHB(L,NT),ATOXFBECHW(L,NT)
c
        WRITE(2,101)IL(L),JL(L),(ATOXPFBW(L,NS,NT),NS=1,NTMP),
     &  ATOXFDFBW(L,NT),ATOXCDFBW(L,NT)

        WRITE(3,101)IL(L),JL(L),(ATOXPFBWP(L,NS,NT),NS=1,NTMP),
     &  ATOXFDFBWP(L,NT),ATOXCDFBWP(L,NT)
C
        WRITE(4,101)IL(L),JL(L),(ATOXPFBWN(L,NS,NT),NS=1,NTMP),
     &  ATOXFDFBWN(L,NT),ATOXCDFBWN(L,NT)
c
        WRITE(11,101)IL(L),JL(L),ATOXFDFBWAD(L,NT),ATOXCDFBWAD(L,NT)
C
        WRITE(12,101)IL(L),JL(L),ATOXFDFBWADP(L,NT),ATOXCDFBWADP(L,NT)
C
        WRITE(13,101)IL(L),JL(L),ATOXFDFBWADN(L,NT),ATOXCDFBWADN(L,NT)
C
        WRITE(14,101)IL(L),JL(L),      
     &  (ASEDFWX(L,NS),NS=1,NTMP),(ASEDFWY(L,NS),NS=1,NTMP),
     &  (ASEDFBLX(L,NS),NS=1,NSND),(ASEDFBLY(L,NS),NS=1,NSND)
C
C       'TOXALL_PFWCADV.OUT'
C
C        WRITE(21,101)IL(L),JL(L),      
C     &  (ATOXPFWX(L,NS,NT),NS=1,NTMP),(ATOXPFWY(L,NS,NT),NS=1,NTMP)
C
C       'TOXALL_FDWCADV.OUT'
C
C        WRITE(22,101)IL(L),JL(L),ATOXFDFWX(L,NT),ATOXFDFWY(L,NT),
C     &   ATOXCDFWX(L,NT),ATOXCDFWY(L,NT)      
C
C       'TOXALL_PFBEDLD.OUT'
C
C        WRITE(23,101)IL(L),JL(L),      
C     &  (ATOXPFBLX(L,NS,NT),NS=1,NSND),(ATOXPFBLY(L,NS,NT),NS=1,NSND)
C
C       'TOXALL_SORSINK.OUT'
C 
C         WRITE(24,101)IL(L),JL(L),ATOXSOUR(L,NT),ATOXSINK(L,NT),
C     &                           ATOXVOL(L,NT)      
C
C       'TOXALL_PFBD2WC.OUT'
C
C        WRITE(25,101)IL(L),JL(L),(ATOXPFBW(L,NS,NT),NS=1,NTMP),
C     &    (ATOXPFBWP(L,NS,NT),NS=1,NTMP),(ATOXPFBWN(L,NS,NT),NS=1,NTMP)       
C        
C       'TOXALL_FDBD2WC.OUT'
C
C        WRITE(26,101)IL(L),JL(L),ATOXFDFBW(L,NT),ATOXFDFBWP(L,NT),ATOXFDFBWN(L,NT),
C     &      ATOXCDFBW(L,NT),ATOXCDFBWP(L,NT),ATOXCDFBWN(L,NT)   
C        
C       'TOXALL_BANKERO.OUT'
C
C         WRITE(27,101)IL(L),JL(L),ATOXFBEBKB(L,NT),
C     &   ATOXFBECHB(L,NT),ATOXFBECHW(L,NT)      
C
      ENDDO
C
      CLOSE(1)
      CLOSE(2)
      CLOSE(3)
      CLOSE(4)
      CLOSE(11)
      CLOSE(12)
      CLOSE(13)
      CLOSE(14)
C
C  DEBUGGING FILES
C
C       DO IUNIT=21,27
C         CLOSE(IUNIT)
C       ENDDO
C
  100 FORMAT(F10.3)
  101 FORMAT(2I6,64E14.6)
C
C**********************************************************************C

      RETURN
      END
