C
C**********************************************************************C
C**********************************************************************C
C**********************************************************************C
C
      SUBROUTINE VELPLTH
C
C **  THIS SUBROUTINE IS PART OF  EFDC-FULL VERSION 1.0a 
C
C **  LAST MODIFIED BY JOHN HAMRICK ON 1 NOVEMBER 2001
C
C----------------------------------------------------------------------C
C
C CHANGE RECORD
C DATE MODIFIED     BY                 DATE APPROVED    BY
C 05/02/2002        John Hamrick       05/01/2002       John Hamrick
C  added real flags RSSBCE(L),RSSBCW(L),RSSBCN(L),RSSBCS(L)
C  to modified  the outputed cell center velocity for cells have source/sinks
C----------------------------------------------------------------------C
C
C **  SUBROUTINE VELPLTH WRITES A HORIZONTAL INSTANTANEOUS VELOCITY
C **  VECTOR FILE 
C
C**********************************************************************C
C
      INCLUDE 'EFDC.PAR'
      INCLUDE 'EFDC.CMN'
C
C**********************************************************************C
C
      REAL DBS(10)
	DIMENSION UPROFILE(KCM),VPROFILE(KCM)
      CHARACTER*80 TITLE1,TITLE2,TITLE3,TITLE4,TITLE5,TITLE6,TITLE7
C
C**********************************************************************C
C
      IF(IVPHXY.LE.2)THEN
C
      IF(JSVPH.NE.1)GOTO 300
C
C----------------------------------------------------------------------C
C
C **  WRITE HEADINGS
C
      TITLE1='INSTANTANEOUS HORIZ VELOCITY CM/S '
      TITLE2='INSTANTANEOUS BOTTOM STRESS CM2/S2'
      TITLE3='BEDLOAD TRANSPORT KG/S'
      TITLE4='DEPTH INTEGRAED SED TRANS KG/S'
      TITLE5='EFFECTIVE BOTTOM ROUGHNESS CM'
      TITLE6='CURRENT SHEAR VELOCITY CM/S'
      TITLE7='WAVE-CURRENT SHEAR VELOCITY CM/S'
      IF(ISVPH.EQ.1) LINES1=LA-1
      IF(ISVPH.EQ.2) LINES1=NRC
      IF(ISVPH.EQ.3) LINES1=NBC
      LEVELS=2
      LEVELT=1
      DBS(1)=0.
      DBS(2)=99.
C
      OPEN(10,FILE='VELVECH.OUT',STATUS='UNKNOWN')
      CLOSE(10,STATUS='DELETE')
      OPEN(10,FILE='VELVECH.OUT',STATUS='UNKNOWN')
      WRITE (10,99) TITLE1
      WRITE (10,101)LINES1,LEVELS
      WRITE (10,250)(DBS(L),L=1,LEVELS)
      CLOSE(10)
C
      OPEN(11,FILE='VELVECH.COC',STATUS='UNKNOWN')
      CLOSE(11,STATUS='DELETE')
      OPEN(11,FILE='VELVECH.COC',STATUS='UNKNOWN')
      WRITE (11,99) TITLE1
      WRITE (11,101)LINES1,LEVELS
      WRITE (11,250)(DBS(L),L=1,LEVELS)
      CLOSE(11)
C
      OPEN(10,FILE='TAUVECH.OUT',STATUS='UNKNOWN')
      CLOSE(10,STATUS='DELETE')
      OPEN(10,FILE='TAUVECH.OUT',STATUS='UNKNOWN')
      WRITE (10,99) TITLE2
      WRITE (10,101)LINES1,LEVELT
      WRITE (10,250)(DBS(L),L=1,LEVELT)
      CLOSE(10)
C
      IF(ISTRAN(7).GT.0)THEN
      OPEN(10,FILE='SBLVECH.OUT',STATUS='UNKNOWN')
      CLOSE(10,STATUS='DELETE')
      OPEN(10,FILE='SBLVECH.OUT',STATUS='UNKNOWN')
      WRITE (10,99) TITLE3
      WRITE (10,101)LINES1,LEVELS
      WRITE (10,250)(DBS(L),L=1,LEVELS)
      CLOSE(10)
	ENDIF
C
C      OPEN(10,FILE='TSTVECH.OUT',STATUS='UNKNOWN')
C      CLOSE(10,STATUS='DELETE')
C      OPEN(10,FILE='TSTVECH.OUT',STATUS='UNKNOWN')
C      WRITE (10,99) TITLE4
C      WRITE (10,101)LINES1,LEVELT
C      WRITE (10,250)(DBS(L),L=1,LEVELT)
C      CLOSE(10)
C
      IF(ISWAVE.GE.1)THEN
      OPEN(10,FILE='ZBREFFH.OUT',STATUS='UNKNOWN')
      CLOSE(10,STATUS='DELETE')
      OPEN(10,FILE='ZBREFFH.OUT',STATUS='UNKNOWN')
      WRITE (10,99) TITLE5
      WRITE (10,101)LINES1,LEVELT
      WRITE (10,250)(DBS(L),L=1,LEVELT)
      CLOSE(10)
	ENDIF
C
      IF(ISWAVE.GE.1)THEN
      OPEN(10,FILE='CCUSTRH.OUT',STATUS='UNKNOWN')
      CLOSE(10,STATUS='DELETE')
      OPEN(10,FILE='CCUSTRH.OUT',STATUS='UNKNOWN')
      WRITE (10,99) TITLE6
      WRITE (10,101)LINES1,LEVELT
      WRITE (10,250)(DBS(L),L=1,LEVELT)
      CLOSE(10)
	ENDIF
C
      IF(ISWAVE.GE.1)THEN
      OPEN(10,FILE='WCUSTRH.OUT',STATUS='UNKNOWN')
      CLOSE(10,STATUS='DELETE')
      OPEN(10,FILE='WCUSTRH.OUT',STATUS='UNKNOWN')
      WRITE (10,99) TITLE7
      WRITE (10,101)LINES1,LEVELT
      WRITE (10,250)(DBS(L),L=1,LEVELT)
      CLOSE(10)
	ENDIF
C
      JSVPH=0
C
C----------------------------------------------------------------------C
C
  300 CONTINUE 
C
      IF(ISDYNSTP.EQ.0)THEN
        TIME=DT*FLOAT(N)+TCON*TBEGIN
        TIME=TIME/TCON    
      ELSE
        TIME=TIMESEC/TCON 
      ENDIF
C
      OPEN(10,FILE='VELVECH.OUT',POSITION='APPEND')
      WRITE (10,100)N,TIME
      OPEN(11,FILE='TAUVECH.OUT',POSITION='APPEND')
      WRITE (11,100)N,TIME
	IF(ISTRAN(7).GT.0)THEN
       OPEN(12,FILE='SBLVECH.OUT',POSITION='APPEND')
       WRITE (12,100)N,TIME
	ENDIF
C      OPEN(13,FILE='TSTVECH.OUT',POSITION='APPEND')
C      WRITE (13,100)N,TIME
	IF(ISWAVE.GE.1)THEN
        OPEN(14,FILE='ZBREFFH.OUT',POSITION='APPEND')
        WRITE (14,100)N,TIME
        OPEN(15,FILE='CCUSTRH.OUT',POSITION='APPEND')
        WRITE (15,100)N,TIME
        OPEN(16,FILE='WCUSTRH.OUT',POSITION='APPEND')
        WRITE (16,100)N,TIME
	ENDIF
      OPEN(20,FILE='VELVECH.COC',POSITION='APPEND')
      WRITE (20,100)N,TIME
C
      QBOTTMP=100./CTURB3
C
      IF(IVPHXY.EQ.0)THEN
       DO L=2,LA
       LN=LNC(L)
       UTMPS=50.*STCUV(L)*(RSSBCE(L)*U(L+1,KC)+RSSBCW(L)*U(L,KC))
       VTMPS=50.*STCUV(L)*(RSSBCN(L)*V(LN ,KC)+RSSBCS(L)*V(L,KC))
       VELEKC=CUE(L)*UTMPS+CVE(L)*VTMPS
       VELNKC=CUN(L)*UTMPS+CVN(L)*VTMPS
       UTMPB=50.*STCUV(L)*(RSSBCE(L)*U(L+1,1)+RSSBCW(L)*U(L,1))
       VTMPB=50.*STCUV(L)*(RSSBCN(L)*V(LN ,1)+RSSBCS(L)*V(L,1))
       VELEKB=CUE(L)*UTMPB+CVE(L)*VTMPB
       VELNKB=CUN(L)*UTMPB+CVN(L)*VTMPB
       UTMPA=50.*STCUV(L)*(RSSBCE(L)*UHE(L+1)*HUI(L+1)
     &                    +RSSBCW(L)*UHE(L)*HUI(L))
       VTMPA=50.*STCUV(L)*(RSSBCN(L)*VHE(LN )*HVI(LN )
     &                    +RSSBCS(L)*VHE(L)*HVI(L))
       TUTMP=5000.*STCUV(L)*(RSSBCE(L)*TBX(L+1)+RSSBCW(L)*TBX(L))
       TVTMP=5000.*STCUV(L)*(RSSBCN(L)*TBY(LN )+RSSBCS(L)*TBY(L))
       VELEAV=CUE(L)*UTMPA+CVE(L)*VTMPA
       VELNAV=CUN(L)*UTMPA+CVN(L)*VTMPA
c write velvech.out
       IF(KC.GT.1)WRITE(10,201)
     $              VELEKC,VELNKC,VELEKB,VELNKB,VELEAV,VELNAV
       IF(KC.EQ.1)WRITE(10,200)IL(L),JL(L),VELEKB,VELNKB
c write velvech.coc
       IF(KC.GT.1)WRITE(20,201)
     $       UTMPS,VTMPS,UTMPB,VTMPB,UTMPA,VTMPA,TUTMP,TVTMP
       IF(KC.EQ.1)WRITE(20,200)IL(L),JL(L),UTMPS,VTMPS,TUTMP,TVTMP
       UTMP=5000.*STCUV(L)*(RSSBCE(L)*TBX(L+1)+RSSBCW(L)*TBX(L))
       VTMP=5000.*STCUV(L)*(RSSBCN(L)*TBY(LN )+RSSBCS(L)*TBY(L))
       VELEKC=CUE(L)*UTMP+CVE(L)*VTMP
       VELNKC=CUN(L)*UTMP+CVN(L)*VTMP
	 TMPV1=10000.*TAUB(L)
	 TMPV2=10000.*TAUBSED(L)
	 TMPV3=10000.*TAUBSND(L)
	 TMPV4=100.*WSETFLOC(L,1)
c write tauvech.out
       WRITE(11,201)VELEKC,VELNKC,TMPV1,TMPV2,TMPV3,TMPV4
       IF(ISTRAN(7).GE.1) THEN
         UTMP=0.0005*STCUV(L)*(RSSBCE(L)*QSBDLDX(L+1,1)
     $                       +RSSBCW(L)*QSBDLDX(L  ,1))
         VTMP=0.0005*STCUV(L)*(RSSBCN(L)*QSBDLDY(LN ,1)
     $                       +RSSBCS(L)*QSBDLDY(L  ,1))
         VELEKC=CUE(L)*UTMP+CVE(L)*VTMP
         VELNKC=CUN(L)*UTMP+CVN(L)*VTMP
         UTMP=0.0005*STCUV(L)*(RSSBCE(L)*QSBDLDX(L+1,2)
     &                       +RSSBCW(L)*QSBDLDX(L,2)) 
         VTMP=0.0005*STCUV(L)*(RSSBCN(L)*QSBDLDY(LN ,2)
     &                       +RSSBCS(L)*QSBDLDY(L,2)) 
         VELEKB=CUE(L)*UTMP+CVE(L)*VTMP
         VELNKB=CUN(L)*UTMP+CVN(L)*VTMP
         WRITE(12,200)VELEKC,VELNKC,
     $                VELEKB,VELNKB
       END IF
       IF(ISWAVE.GE.2)THEN
         ZBREFF=100.*ZBRE(L)
         WRITE(14,201)ZBREFF
         QTURBC=QBOTTMP*SQRT(QQ(L,0))
         WRITE(15,201)QTURBC
         QTURBC=QBOTTMP*QQWV2(L)
         WRITE(16,201)QTURBC
       ENDIF
       ENDDO
      ENDIF
C
      IF(IVPHXY.EQ.1)THEN
       DO L=2,LA
       LN=LNC(L)
       UTMPS=50.*STCUV(L)*(RSSBCE(L)*U(L+1,KC)+RSSBCW(L)*U(L,KC))
       VTMPS=50.*STCUV(L)*(RSSBCN(L)*V(LN ,KC)+RSSBCS(L)*V(L,KC))
       VELEKC=CUE(L)*UTMPS+CVE(L)*VTMPS
       VELNKC=CUN(L)*UTMPS+CVN(L)*VTMPS
       UTMPB=50.*STCUV(L)*(RSSBCE(L)*U(L+1,1)+RSSBCW(L)*U(L,1))
       VTMPB=50.*STCUV(L)*(RSSBCN(L)*V(LN ,1)+RSSBCS(L)*V(L,1))
       VELEKB=CUE(L)*UTMPB+CVE(L)*VTMPB
       VELNKB=CUN(L)*UTMPB+CVN(L)*VTMPB
       UTMPA=50.*STCUV(L)*(RSSBCE(L)*UHE(L+1)*HUI(L+1)
     &                    +RSSBCW(L)*UHE(L)*HUI(L))
       VTMPA=50.*STCUV(L)*(RSSBCN(L)*VHE(LN )*HVI(LN )
     &                    +RSSBCS(L)*VHE(L)*HVI(L))
       TUTMP=5000.*STCUV(L)*(RSSBCE(L)*TBX(L+1)+RSSBCW(L)*TBX(L))
       TVTMP=5000.*STCUV(L)*(RSSBCN(L)*TBY(LN )+RSSBCS(L)*TBY(L))
       VELEAV=CUE(L)*UTMPA+CVE(L)*VTMPA
       VELNAV=CUN(L)*UTMPA+CVN(L)*VTMPA
c write velvech.out
       IF(KC.GT.1)WRITE(10,200)IL(L),JL(L),
     $              VELEKC,VELNKC,VELEKB,VELNKB,VELEAV,VELNAV
       IF(KC.EQ.1)WRITE(10,200)IL(L),JL(L),VELEKB,VELNKB
c write velvech.coc
       IF(KC.GT.1)WRITE(20,200)IL(L),JL(L),
     $       UTMPS,VTMPS,UTMPB,VTMPB,UTMPA,VTMPA,TUTMP,TVTMP
       IF(KC.EQ.1)WRITE(20,200)IL(L),JL(L),UTMPS,VTMPS,TUTMP,TVTMP
       UTMP=5000.*STCUV(L)*(RSSBCE(L)*TBX(L+1)+RSSBCW(L)*TBX(L))
       VTMP=5000.*STCUV(L)*(RSSBCN(L)*TBY(LN )+RSSBCS(L)*TBY(L))
       VELEKC=CUE(L)*UTMP+CVE(L)*VTMP
       VELNKC=CUN(L)*UTMP+CVN(L)*VTMP
	 TMPV1=10000.*TAUB(L)
	 TMPV2=10000.*TAUBSED(L)
	 TMPV3=10000.*TAUBSND(L)
	 TMPV4=100.*WSETFLOC(L,1)
c write tauvech.out
       WRITE(11,200)IL(L),JL(L),VELEKC,VELNKC,TMPV1,TMPV2,TMPV3,TMPV4
       IF(ISTRAN(7).GE.1) THEN
         UTMP=0.0005*STCUV(L)*(RSSBCE(L)*QSBDLDX(L+1,1)
     $                       +RSSBCW(L)*QSBDLDX(L  ,1))
         VTMP=0.0005*STCUV(L)*(RSSBCN(L)*QSBDLDY(LN ,1)
     $                       +RSSBCS(L)*QSBDLDY(L  ,1))
         VELEKC=CUE(L)*UTMP+CVE(L)*VTMP
         VELNKC=CUN(L)*UTMP+CVN(L)*VTMP
         UTMP=0.0005*STCUV(L)*(RSSBCE(L)*QSBDLDX(L+1,2)
     &                       +RSSBCW(L)*QSBDLDX(L,2)) 
         VTMP=0.0005*STCUV(L)*(RSSBCN(L)*QSBDLDY(LN ,2)
     &                       +RSSBCS(L)*QSBDLDY(L,2)) 
         VELEKB=CUE(L)*UTMP+CVE(L)*VTMP
         VELNKB=CUN(L)*UTMP+CVN(L)*VTMP
         WRITE(12,200)IL(L),JL(L),VELEKC,VELNKC,
     $                VELEKB,VELNKB
       END IF
       IF(ISWAVE.GE.2)THEN
         ZBREFF=100.*ZBRE(L)
         WRITE(14,200)IL(L),JL(L),DLON(L),DLAT(L),ZBREFF
         QTURBC=QBOTTMP*SQRT(QQ(L,0))
         WRITE(15,200)IL(L),JL(L),DLON(L),DLAT(L),QTURBC
         QTURBC=QBOTTMP*QQWV2(L)
         WRITE(16,200)IL(L),JL(L),DLON(L),DLAT(L),QTURBC
       ENDIF
       ENDDO
      ENDIF
C
      IF(IVPHXY.EQ.2)THEN 
       DO LR=1,NRC
       L=LRC(LR)
       LN=LNC(L)
       UTMPS=50.*STCUV(L)*(RSSBCE(L)*U(L+1,KC)+RSSBCW(L)*U(L,KC))
       VTMPS=50.*STCUV(L)*(RSSBCN(L)*V(LN ,KC)+RSSBCS(L)*V(L,KC))
       VELEKC=CUE(L)*UTMPS+CVE(L)*VTMPS
       VELNKC=CUN(L)*UTMPS+CVN(L)*VTMPS
       UTMPB=50.*STCUV(L)*(RSSBCE(L)*U(L+1,1)+RSSBCW(L)*U(L,1))
       VTMPB=50.*STCUV(L)*(RSSBCN(L)*V(LN ,1)+RSSBCS(L)*V(L,1))
       VELEKB=CUE(L)*UTMPB+CVE(L)*VTMPB
       VELNKB=CUN(L)*UTMPB+CVN(L)*VTMPB
       UTMPA=50.*STCUV(L)*(RSSBCE(L)*UHE(L+1)*HUI(L+1)
     &                    +RSSBCW(L)*UHE(L)*HUI(L))
       VTMPA=50.*STCUV(L)*(RSSBCN(L)*VHE(LN )*HVI(LN )
     &                    +RSSBCS(L)*VHE(L)*HVI(L))
       TUTMP=5000.*STCUV(L)*(RSSBCE(L)*TBX(L+1)+RSSBCW(L)*TBX(L))
       TVTMP=5000.*STCUV(L)*(RSSBCN(L)*TBY(LN )+RSSBCS(L)*TBY(L))
       VELEAV=CUE(L)*UTMPA+CVE(L)*VTMPA
       VELNAV=CUN(L)*UTMPA+CVN(L)*VTMPA
       IF(KC.GT.1) WRITE(10,200)IL(L),JL(L),DLON(L),DLAT(L),
     $         VELEKC,VELNKC,VELEKB,VELNKB,VELEAV,VELNAV
       IF(KC.EQ.1) WRITE(10,200)IL(L),JL(L),DLON(L),DLAT(L),
     $         VELEKC,VELNKC
       IF(KC.GT.1) WRITE(20,200)IL(L),JL(L),DLON(L),DLAT(L),
     $      UTMPS,VTMPS,UTMPB,VTMPB,UTMPA,VTMPA,TUTMP,TVTMP
       IF(KC.EQ.1) WRITE(20,200)IL(L),JL(L),DLON(L),DLAT(L),
     $              UTMPS,VTMPS,TUTMP,TVTMP
       UTMP=5000.*STCUV(L)*(RSSBCE(L)*TBX(L+1)+RSSBCW(L)*TBX(L))
       VTMP=5000.*STCUV(L)*(RSSBCN(L)*TBY(LN )+RSSBCS(L)*TBY(L))
       VELEKC=CUE(L)*UTMP+CVE(L)*VTMP
       VELNKC=CUN(L)*UTMP+CVN(L)*VTMP
	 TMPV1=10000.*TAUB(L)
	 TMPV2=10000.*TAUBSED(L)
	 TMPV3=10000.*TAUBSND(L)
	 TMPV4=100.*WSETFLOC(L,1)
       WRITE(11,200)IL(L),JL(L),DLON(L),DLAT(L),VELEKC,VELNKC,TMPV1,
     $              TMPV2,TMPV3,TMPV4
       IF(ISTRAN(7).GE.1) THEN
         UTMP=0.0005*STCUV(L)*(RSSBCE(L)*QSBDLDX(L+1,1)
     $                       +RSSBCW(L)*QSBDLDX(L  ,1))
         VTMP=0.0005*STCUV(L)*(RSSBCN(L)*QSBDLDY(LN ,1)
     $                       +RSSBCS(L)*QSBDLDY(L  ,1))
         VELEKC=CUE(L)*UTMP+CVE(L)*VTMP
         VELNKC=CUN(L)*UTMP+CVN(L)*VTMP
         UTMP=0.0005*STCUV(L)*(RSSBCE(L)*QSBDLDX(L+1,2)
     &                       +RSSBCW(L)*QSBDLDX(L,2)) 
         VTMP=0.0005*STCUV(L)*(RSSBCN(L)*QSBDLDY(LN ,2)
     &                       +RSSBCS(L)*QSBDLDY(L,2)) 
         VELEKB=CUE(L)*UTMP+CVE(L)*VTMP
         VELNKB=CUN(L)*UTMP+CVN(L)*VTMP
         WRITE(12,200)IL(L),JL(L),DLON(L),DLAT(L),VELEKC,VELNKC,
     $                VELEKB,VELNKB
       END IF
       IF(ISWAVE.GE.2)THEN
         ZBREFF=100.*ZBRE(L)
         WRITE(14,200)IL(L),JL(L),DLON(L),DLAT(L),ZBREFF
         QTURBC=QBOTTMP*SQRT(QQ(L,0))
         WRITE(15,200)IL(L),JL(L),DLON(L),DLAT(L),QTURBC
         QTURBC=QBOTTMP*QQWV2(L)
         WRITE(16,200)IL(L),JL(L),DLON(L),DLAT(L),QTURBC
       END IF
       END DO
      END IF
C
      CLOSE(10)
      CLOSE(11)
      IF(ISTRAN(7).GT.0)CLOSE(12)
      CLOSE(13)
      CLOSE(14)
      CLOSE(15)
      CLOSE(16)
      CLOSE(20)
C
      ENDIF
C
C**********************************************************************C
C
C **  WRITE EFDC EXPLORER FORMAT OUTPUT
C
      IF(IVPHXY.EQ.3) CALL VELPLTHE
C
C**********************************************************************C
C
   99 FORMAT(A80)
  100 FORMAT(I10,F12.4)
  101 FORMAT(2I10)
  200 FORMAT(2I5,1X,10E14.6)
  201 FORMAT(8E14.6)
  250 FORMAT(12E12.4)
CMRM  200 FORMAT(2I5,1X,1p,6E13.5) 
CMRM  250 FORMAT(1p,12E11.3)
C
C**********************************************************************C
C
      RETURN
      END
